import test from 'node:test';
import assert from 'node:assert/strict';
import { createEditorDocument, createRasterLayer } from '../src/editor-document.js';
import { CommandHistory } from '../src/editor-history.js';
import { createAddGuideCommand, createCanvasPreferencesCommand, createCropDocumentCommand, createRemoveGuideCommand, createResizeDocumentCommand, createResizeLayerCommand, createSetTransformCommand, getCanvasMetadata } from '../src/editor-canvas-commands.js';
function fixture(){const layer=createRasterLayer({id:'photo',assetId:'asset-photo',width:800,height:600,transform:{x:100,y:80},mask:{assetId:'mask-photo',opacity:.8}}),documentModel=createEditorDocument({id:'doc',width:1000,height:800,layers:[layer],activeLayerId:'photo',selectedLayerIds:['photo']});return{documentModel,history:new CommandHistory}}
test('crop preserves layers and masks and is fully undoable',()=>{const{documentModel,history}=fixture();history.execute(createCropDocumentCommand({x:50,y:30,width:640,height:480}),documentModel);assert.equal(documentModel.width,640);assert.equal(documentModel.height,480);assert.equal(documentModel.getLayer('photo').transform.x,50);assert.equal(documentModel.getLayer('photo').transform.y,50);assert.equal(documentModel.getLayer('photo').mask.assetId,'mask-photo');assert.equal(documentModel.metadata.canvasGeometryLocked,true);history.undo(documentModel);assert.equal(documentModel.width,1000);assert.equal(documentModel.getLayer('photo').transform.x,100);assert.equal(documentModel.getLayer('photo').mask.opacity,.8)});
test('document resize scales layer placement and transform through history',()=>{const{documentModel,history}=fixture();history.execute(createResizeDocumentCommand(500,400,{scaleLayers:true,interpolation:'medium'}),documentModel);assert.equal(documentModel.width,500);assert.equal(documentModel.height,400);assert.equal(documentModel.getLayer('photo').transform.x,50);assert.equal(documentModel.getLayer('photo').transform.y,40);assert.equal(documentModel.getLayer('photo').transform.scaleX,.5);assert.equal(documentModel.metadata.interpolation,'medium');assert.equal(documentModel.metadata.canvasGeometryLocked,true);history.undo(documentModel);assert.equal(documentModel.width,1000);assert.equal(documentModel.getLayer('photo').transform.scaleX,1)});
test('layer resize and perspective transform preserve the mask and support undo',()=>{const{documentModel,history}=fixture();history.execute(createResizeLayerCommand('photo',320,240,{interpolation:'nearest'}),documentModel);history.execute(createSetTransformCommand('photo',{x:5,y:7,rotation:12,skewX:4,perspectiveX:.3,perspectiveY:-.2}),documentModel);const layer=documentModel.getLayer('photo');assert.deepEqual({width:layer.content.width,height:layer.content.height},{width:320,height:240});assert.equal(layer.metadata.interpolation,'nearest');assert.equal(layer.metadata.manualSize,true);assert.equal(layer.transform.perspectiveX,.3);assert.equal(layer.transform.perspectiveY,-.2);assert.equal(layer.mask.assetId,'mask-photo');history.undo(documentModel);assert.equal(documentModel.getLayer('photo').transform.perspectiveX,0);history.undo(documentModel);assert.equal(documentModel.getLayer('photo').content.width,800)});
test('guides, grid and snapping preferences are undoable',()=>{const{documentModel,history}=fixture();history.execute(createCanvasPreferencesCommand({gridEnabled:true,snapping:false,guidesVisible:false}),documentModel);history.execute(createAddGuideCommand('vertical',120),documentModel);history.execute(createAddGuideCommand('horizontal',75),documentModel);let canvas=getCanvasMetadata(documentModel);assert.equal(canvas.gridEnabled,true);assert.equal(canvas.snapping,false);assert.deepEqual(canvas.guides,{vertical:[120],horizontal:[75]});history.execute(createRemoveGuideCommand('vertical',121,2),documentModel);assert.deepEqual(getCanvasMetadata(documentModel).guides.vertical,[]);history.undo(documentModel);assert.deepEqual(getCanvasMetadata(documentModel).guides.vertical,[120]);history.undo(documentModel);assert.deepEqual(getCanvasMetadata(documentModel).guides.horizontal,[])});
