import test from 'node:test';
import assert from 'node:assert/strict';
import { depthBlurRadius, depthMapStats, depthWeights, invertDepthMap, normalizeDepthOutput, paintDepthMap, sampleDepth, scaleDepthMap } from '../src/editor-depth-map.js';
import { applyAtmosphere, applyDepthEffectTiled, applyLensBlur, applyRelight, createDepthEffect } from '../src/editor-depth-effects.js';
import { blendEffect, isDepthEffectLayer } from '../src/editor-depth-renderer.js';
import { addDepthEffectCommand, replaceDepthMapAssetCommand, setDocumentDepthMapCommand } from '../src/editor-depth-commands.js';
import { createEditorDocument, createRasterLayer } from '../src/editor-document.js';
import { CommandHistory } from '../src/editor-history.js';

const rgba=(w,h,fn)=>{const out=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++)out.set(fn(x,y),(y*w+x)*4);return out;};

test('normalizes, scales, samples and inverts depth output',()=>{const normalized=normalizeDepthOutput({data:Float32Array.from([10,20,30,40]),width:2,height:2});assert.deepEqual([...normalized.data],[0,85,170,255]);const scaled=scaleDepthMap(normalized.data,2,2,4,4);assert.equal(scaled.length,16);assert.ok(sampleDepth(scaled,4,4,3,3)>.9);assert.equal(invertDepthMap(Uint8Array.from([0,255]),2,1)[0],255);});
test('accepts RGBA depth images returned by browser pipelines',()=>{const normalized=normalizeDepthOutput({data:Uint8ClampedArray.from([0,0,0,255,255,255,255,255]),width:2,height:1});assert.deepEqual([...normalized.data],[0,255]);});
test('maps distance from focus to blur radius',()=>{assert.equal(depthBlurRadius(.5,.5,{aperture:20,focusRange:.1,maxRadius:18}),0);assert.ok(depthBlurRadius(.9,.5,{aperture:20,focusRange:.1,maxRadius:18})>5);assert.equal(depthBlurRadius(1,0,{aperture:50,focusRange:0,maxRadius:12}),12);});
test('depth weights separate foreground background and focus',()=>{const near=depthWeights(.1,.5,.1),far=depthWeights(.9,.5,.1),focus=depthWeights(.5,.5,.1);assert.ok(near.foreground>near.background);assert.ok(far.background>far.foreground);assert.equal(focus.focused,1);});
test('manual depth brush edits one local region',()=>{const map=new Uint8Array(400).fill(128);const painted=paintDepthMap(map,20,20,[{x:10,y:10,pressure:1}],{depth:1,size:8,hardness:1,opacity:1});assert.equal(painted[210],255);assert.equal(painted[0],128);assert.ok(depthMapStats(painted,20,20).mean>.5);});
test('lens blur protects focus and changes distant pixels',()=>{const width=12,height=4;const source=rgba(width,height,x=>x<6?[255,255,255,255]:[0,0,0,255]);const depth=Uint8Array.from({length:width*height},(_,i)=>(i%width)<6?128:255);const output=applyLensBlur(source,depth,width,height,{focusDepth:.5,focusRange:.08,aperture:10,maxRadius:8,bokeh:0,depthBins:5});assert.deepEqual([...output.slice(8,11)],[255,255,255]);assert.ok(output[(2*width+7)*4]>0);});
test('relighting and atmosphere follow depth',()=>{const source=rgba(2,1,()=>[100,100,100,255]);const depth=Uint8Array.from([0,255]);const relit=applyRelight(source,depth,2,1,{focusDepth:.5,focusRange:.08,foregroundExposure:1,backgroundExposure:-1,warmth:.2,contrast:0});assert.ok(relit[0]>relit[4]);const fog=applyAtmosphere(source,depth,2,1,{density:1,startDepth:.4,color:[220,230,240],lightStrength:0,lightDepth:.6});assert.ok(fog[4]>fog[0]);});
test('tiled depth rendering matches dimensions and avoids empty seams',()=>{const width=70,height=54;const source=rgba(width,height,(x,y)=>[x*3%255,y*4%255,120,255]);const depth=Uint8Array.from({length:width*height},(_,i)=>Math.round((i%width)/(width-1)*255));const output=applyDepthEffectTiled(source,depth,width,height,createDepthEffect('relight',{foregroundExposure:.3,backgroundExposure:-.2}),{tileSize:64,overlap:8});assert.equal(output.length,source.length);for(let i=3;i<output.length;i+=4)assert.equal(output[i],255);});
test('depth effect layers and map edits participate in undo redo',()=>{const base=createRasterLayer({id:'base',assetId:'asset',width:4,height:4});const doc=createEditorDocument({width:4,height:4,layers:[base],activeLayerId:'base'});const history=new CommandHistory();history.execute(setDocumentDepthMapCommand({assetId:'depth-a',width:4,height:4}),doc);history.execute(addDepthEffectCommand('lens-blur','depth-a'),doc);assert.ok(doc.layers.find(isDepthEffectLayer));history.execute(replaceDepthMapAssetCommand({assetId:'depth-b',width:4,height:4}),doc);assert.equal(doc.layers.find(isDepthEffectLayer).metadata.depthAssetId,'depth-b');history.undo(doc);assert.equal(doc.layers.find(isDepthEffectLayer).metadata.depthAssetId,'depth-a');history.redo(doc);assert.equal(doc.metadata.depthMap.assetId,'depth-b');});
test('effect blending preserves alpha and supports opacity',()=>{const output=blendEffect(Uint8ClampedArray.from([100,100,100,77]),Uint8ClampedArray.from([200,50,150,255]),.5,'normal');assert.deepEqual([...output],[150,75,125,77]);});
