import test from 'node:test';
import assert from 'node:assert/strict';
import { createEditorDocument, createRasterLayer } from '../src/editor-document.js';
import { CommandHistory } from '../src/editor-history.js';
import { createAppendEraseStrokeCommand, createBrushStroke, createGradientFill, createPaintOperationCommand, createSolidFill, resampleStroke } from '../src/editor-paint.js';
import { combineSelection, createSelection, rectangleSelection } from '../src/editor-selection.js';
import { createShapeLayerCommand, createTextLayerCommand } from '../src/editor-tools-commands.js';

test('brush stroke is serializable and spacing resamples long segments',()=>{const stroke=createBrushStroke([{x:0,y:0},{x:100,y:0}],{size:20,spacing:.25,hardness:.7,opacity:.5,color:'#123456'}),samples=resampleStroke(stroke.points,stroke.size*stroke.spacing);assert.ok(samples.length>=20);assert.equal(samples[0].x,0);assert.equal(samples.at(-1).x,100);assert.equal(stroke.opacity,.5);assert.doesNotThrow(()=>JSON.stringify(stroke))});
test('one brush gesture creates one paint layer operation and is undoable',()=>{const d=createEditorDocument({width:100,height:80}),h=new CommandHistory,selection=combineSelection(createSelection({width:100,height:80}),rectangleSelection({x:10,y:10,width:30,height:20}));h.execute(createPaintOperationCommand(d,{points:[{x:5,y:5},{x:40,y:20}],size:12,hardness:.8,opacity:1,spacing:.2,color:'#000',selection}),d);assert.equal(d.layers.length,1);assert.equal(d.activeLayer.type,'paint');assert.equal(d.activeLayer.content.strokes.length,1);assert.equal(d.activeLayer.content.strokes[0].selection.entries.length,1);assert.equal(h.undoStack.length,1);h.undo(d);assert.equal(d.layers.length,0);h.redo(d);assert.equal(d.activeLayer.content.strokes.length,1)});
test('solid and gradient fills append to a paint layer and remain undoable',()=>{const d=createEditorDocument({width:50,height:40}),h=new CommandHistory;h.execute(createPaintOperationCommand(d,createSolidFill({color:'#f00',opacity:.8})),d);const id=d.activeLayerId;h.execute(createPaintOperationCommand(d,createGradientFill({x:0,y:0},{x:50,y:40},{type:'radial',colorA:'#000',colorB:'#fff'})),d);assert.equal(d.getLayer(id).content.fills.length,2);assert.equal(d.getLayer(id).content.fills[1].type,'radial');assert.deepEqual(d.getLayer(id).content.operationOrder,d.getLayer(id).content.fills.map(fill=>fill.id));h.undo(d);assert.equal(d.getLayer(id).content.fills.length,1)});
test('eraser stores a nondestructive mask stroke and undo restores the original layer',()=>{const raster=createRasterLayer({id:'photo',assetId:'photo-asset',width:100,height:80}),d=createEditorDocument({width:100,height:80,layers:[raster],activeLayerId:'photo',selectedLayerIds:['photo']}),h=new CommandHistory;h.execute(createAppendEraseStrokeCommand('photo',{points:[{x:10,y:10},{x:30,y:30}],size:20,hardness:1,opacity:1,spacing:.2}),d);assert.equal(d.getLayer('photo').content.assetId,'photo-asset');assert.equal(d.getLayer('photo').mask.metadata.eraseStrokes.length,1);h.undo(d);assert.equal(d.getLayer('photo').mask,null);h.redo(d);assert.equal(d.getLayer('photo').mask.metadata.eraseStrokes[0].tool,'eraser')});
test('text and shape tools create editable scalable layers',()=>{const d=createEditorDocument({width:500,height:400}),h=new CommandHistory;h.execute(createTextLayerCommand({x:20,y:30},{text:'Nagłówek',fontSize:48,fontFamily:'serif',align:'center'}),d);assert.equal(d.activeLayer.type,'text');assert.equal(d.activeLayer.content.text,'Nagłówek');h.execute(createShapeLayerCommand({x:100,y:120,width:200,height:80},{shape:'arrow',fill:null,stroke:'#fff',strokeWidth:6,shadowBlur:10}),d);assert.equal(d.activeLayer.content.shape,'arrow');assert.equal(d.activeLayer.content.width,200);assert.equal(d.activeLayer.content.shadowBlur,10);h.execute(createShapeLayerCommand({x:300,y:250,width:-120,height:-40},{shape:'arrow',fill:null,stroke:'#fff',strokeWidth:4}),d);assert.equal(d.activeLayer.transform.x,300);assert.equal(d.activeLayer.transform.scaleX,-1);assert.equal(d.activeLayer.transform.scaleY,-1)});
test('paint operation order preserves fill, brush and gradient chronology',()=>{const d=createEditorDocument({width:40,height:30}),h=new CommandHistory,base=createSolidFill({id:'fill-a',color:'#f00'});h.execute(createPaintOperationCommand(d,base),d);h.execute(createPaintOperationCommand(d,{id:'stroke-b',points:[{x:1,y:1},{x:10,y:10}],size:5,hardness:1,opacity:1,spacing:.2,color:'#000'}),d);const gradient=createGradientFill({x:0,y:0},{x:40,y:30},{id:'gradient-c',colorA:'#fff',colorB:'#000'});h.execute(createPaintOperationCommand(d,gradient),d);assert.deepEqual(d.activeLayer.content.operationOrder,['fill-a','stroke-b','gradient-c']);h.undo(d);assert.deepEqual(d.activeLayer.content.operationOrder,['fill-a','stroke-b'])});
