import test from 'node:test';
import assert from 'node:assert/strict';
import { BLEND_MODES, createEditorDocument, createGroupLayer, createLayerMask, createRasterLayer, createShapeLayer, createTextLayer } from '../src/editor-document.js';
test('creates a serializable document with dimensions and metadata',()=>{const d=createEditorDocument({width:1920,height:1080,name:'Projekt',metadata:{author:'local'}});assert.equal(d.width,1920);assert.equal(d.height,1080);assert.equal(d.name,'Projekt');assert.deepEqual(d.metadata,{author:'local'});assert.deepEqual(d.layers,[]);assert.doesNotThrow(()=>JSON.stringify(d))});
test('supports raster, text, shape and group layers with common properties',()=>{const layers=[createRasterLayer({id:'r',name:'Raster',assetId:'asset-1'}),createTextLayer({id:'t',text:'Hello'}),createShapeLayer({id:'s',shape:'ellipse'}),createGroupLayer({id:'g',children:[createRasterLayer({id:'nested'})]})];for(const layer of layers){assert.equal(typeof layer.id,'string');assert.equal(layer.visible,true);assert.equal(layer.locked,false);assert.equal(layer.opacity,1);assert.equal(layer.blendMode,'normal');assert.deepEqual(Object.keys(layer.transform),['x','y','scaleX','scaleY','rotation','skewX','skewY','perspectiveX','perspectiveY','originX','originY'])}assert.equal(layers[3].children[0].id,'nested')});
test('adds removes duplicates moves and selects layers',()=>{const d=createEditorDocument({width:100,height:100}),base=d.addLayer(createRasterLayer({id:'base',name:'Base'})),second=d.addLayer(createTextLayer({id:'text',name:'Text'}));assert.equal(d.activeLayerId,second.id);const duplicate=d.duplicateLayer(base.id);assert.notEqual(duplicate.id,base.id);d.removeLayer(duplicate.id);d.removeLayer('text');assert.equal(d.activeLayerId,'base');d.addLayer(createRasterLayer({id:'b'}));d.addLayer(createRasterLayer({id:'c'}));d.moveLayer('base',2);assert.deepEqual(d.layers.map(layer=>layer.id),['b','c','base']);d.setSelectedLayers(['b','base'],'base');assert.deepEqual(d.selectedLayerIds,['b','base'])});
test('updates common properties including clamped perspective',()=>{const d=createEditorDocument({width:10,height:10,layers:[createRasterLayer({id:'layer'})]});d.updateLayer('layer',{visible:false,opacity:.4,locked:true,name:'Renamed',blendMode:'multiply',transform:{x:20,rotation:45,perspectiveX:4,perspectiveY:-4},mask:createLayerMask({assetId:'mask-1',inverted:true}),clipping:{enabled:true,baseLayerId:'base'}});const updated=d.getLayer('layer');assert.equal(updated.visible,false);assert.equal(updated.opacity,.4);assert.equal(updated.locked,true);assert.equal(updated.name,'Renamed');assert.equal(updated.blendMode,'multiply');assert.equal(updated.transform.x,20);assert.equal(updated.transform.rotation,45);assert.equal(updated.transform.perspectiveX,.95);assert.equal(updated.transform.perspectiveY,-.95);assert.equal(updated.mask.assetId,'mask-1');assert.equal(updated.mask.inverted,true);assert.deepEqual(updated.clipping,{enabled:true,baseLayerId:'base'});assert.deepEqual(BLEND_MODES,['normal','multiply','screen','overlay'])});
test('runtime image assets stay outside serialized structure',()=>{const d=createEditorDocument({width:1,height:1,layers:[createRasterLayer({id:'base',assetId:'asset'})]}),asset={width:1,height:1,native:true};d.setRuntimeAsset('asset',asset);assert.equal(d.getRuntimeAsset('asset'),asset);const serialized=JSON.parse(JSON.stringify(d));assert.equal(serialized.runtimeAssets,undefined);assert.equal(serialized.layers[0].content.assetId,'asset')});
test('normalizes invalid document dimensions to at least one pixel',()=>{const d=createEditorDocument({width:0,height:-20});assert.equal(d.width,1);assert.equal(d.height,1)});
