import test from 'node:test';
import assert from 'node:assert/strict';
import { applyMatrix, bilinearPoint, createMatrix, documentToScreen, fitViewport, invertMatrix, perspectiveQuad, screenToDocument, snapPoint, transformedBounds, zoomAtPoint } from '../src/editor-canvas-geometry.js';
const close=(actual,expected,epsilon=1e-8)=>assert.ok(Math.abs(actual-expected)<=epsilon,`${actual} != ${expected}`);
test('zoom keeps the document point under the cursor stable',()=>{const viewport={zoom:1.25,panX:80,panY:-25},cursor={x:340,y:210},before=screenToDocument(cursor,viewport),next=zoomAtPoint(viewport,4,cursor),after=screenToDocument(cursor,next);close(after.x,before.x);close(after.y,before.y);assert.deepEqual(documentToScreen(before,next),cursor)});
test('fit viewport centers the document without enlarging above 100%',()=>{assert.deepEqual(fitViewport({width:1000,height:700},{width:400,height:200},50),{zoom:1,panX:300,panY:250});const small=fitViewport({width:500,height:300},{width:1000,height:800},20);close(small.zoom,.325);close(small.panX,87.5);close(small.panY,20)});
test('affine matrix with rotation, skew and scale has a stable inverse',()=>{const matrix=createMatrix({x:35,y:-12,rotation:27,skewX:8,skewY:-4,scaleX:1.7,scaleY:.75,originX:20,originY:10}),point={x:42,y:19},transformed=applyMatrix(matrix,point),restored=applyMatrix(invertMatrix(matrix),transformed);close(restored.x,point.x,1e-7);close(restored.y,point.y,1e-7);const bounds=transformedBounds({x:0,y:0,width:100,height:40},{x:5,y:6,rotation:30});assert.ok(bounds.width>100);assert.ok(bounds.height>40);assert.equal(bounds.points.length,4)});
test('snapping uses document edges, guides and grid and can be disabled',()=>{const snapped=snapPoint({x:98,y:61},{enabled:true,zoom:2,threshold:8,documentSize:{width:200,height:100},guides:{vertical:[100],horizontal:[60]},gridEnabled:true,gridSize:20});assert.equal(snapped.x,100);assert.equal(snapped.y,60);const raw=snapPoint({x:98,y:61},{enabled:false,documentSize:{width:200,height:100}});assert.deepEqual({x:raw.x,y:raw.y},{x:98,y:61})});
test('perspective quad and bilinear interpolation keep corners and center finite',()=>{const quad=perspectiveQuad(200,100,.5,-.25);assert.equal(quad.length,4);assert.ok(quad[0].x>0);assert.ok(quad[1].y>0);assert.deepEqual(bilinearPoint(quad,0,0),quad[0]);assert.deepEqual(bilinearPoint(quad,1,1),quad[2]);const center=bilinearPoint(quad,.5,.5);assert.ok(Number.isFinite(center.x));assert.ok(Number.isFinite(center.y))});
