import{EmbeddingEngine}from'./embedding-engine.js';import{chunkText,rankChunks,escapeHtml,formatBytes,MODEL_CONFIGS}from'./search-core.js';import{saveDocument,listDocuments,listChunks,removeDocument,clearAll}from'./storage.js';
const $=s=>document.querySelector(s),engine=new EmbeddingEngine(msg=>status(msg));let docs=[];
function status(msg){$('#status').textContent=msg||''}function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,4500)}
function hash(buf){return crypto.subtle.digest('SHA-256',buf).then(d=>[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join(''))}
async function parse(file){if(file.size>25*1024*1024)throw Error('Limit pliku to 25 MB.');const ext=file.name.split('.').pop().toLowerCase();if(ext==='docx'){if(!window.mammoth)throw Error('Moduł DOCX nie został załadowany.');return(await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()})).value}if(ext==='pdf'){const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,p=[];for(let i=1;i<=pdf.numPages;i++){const c=await(await pdf.getPage(i)).getTextContent();p.push(`[Strona ${i}] `+c.items.map(x=>x.str||'').join(' '))}const text=p.join('\n\n').trim();if(!text)throw Error('PDF nie ma warstwy tekstowej; OCR jest w roadmapie.');return text}if(ext==='html'||ext==='htm'){const d=new DOMParser().parseFromString(await file.text(),'text/html');d.querySelectorAll('script,style').forEach(x=>x.remove());return d.body.innerText}return file.text()}
async function ensure(){if(engine.session&&engine.modelKey===$('#model').value)return;const b=await engine.initialize($('#model').value,$('#backend').value);$('#engine').textContent=`Aktywny backend: ${b.toUpperCase()} · ${MODEL_CONFIGS[$('#model').value].label}`;$('#hardware').textContent=b==='npu'?'NPU aktywne':b==='webgpu'?'WebGPU aktywne':'CPU / WASM aktywne';toast(`Silnik gotowy: ${b.toUpperCase()}`)}
async function addText(name,text,size=0,id=null){const parts=chunkText(text);if(!parts.length)throw Error('Brak tekstu do indeksowania.');id=id||await hash(new TextEncoder().encode(text));if(docs.some(d=>d.id===id))throw Error('Ten dokument jest już w bibliotece.');let vectors=null,modelKey='keyword',modelLabel='Słowa kluczowe';try{await ensure();vectors=[];for(let i=0;i<parts.length;i+=3){status(`Indeksowanie ${Math.min(i+3,parts.length)} / ${parts.length}`);vectors.push(...await engine.embed(parts.slice(i,i+3),'passage'))}modelKey=$('#model').value;modelLabel=MODEL_CONFIGS[modelKey].label}catch(e){toast('Model AI niedostępny — zapisuję użyteczny indeks słów.')}const document={id,name,size,chunkCount:parts.length,modelKey,modelLabel,createdAt:new Date().toISOString()};await saveDocument(document,parts.map((text,i)=>({id:`${id}:${i}`,docId:id,docName:name,chunkIndex:i,text,vector:vectors?.[i]||null,modelKey})));status('Gotowe');await refresh()}
async function addFiles(files){for(const f of files){try{status(`Odczyt: ${f.name}`);await addText(f.name,await parse(f),f.size,await hash(await f.arrayBuffer()));toast(`Dodano ${f.name}`)}catch(e){toast(`${f.name}: ${e.message}`)}}}
async function refresh(){docs=await listDocuments();$('#library-meta').textContent=`${docs.length} dokumentów · ${docs.reduce((a,d)=>a+d.chunkCount,0)} fragmentów`;$('#library').innerHTML=docs.length?docs.map(d=>`<div class="doc"><div><b>${escapeHtml(d.name)}</b><small>${d.chunkCount} fragmentów · ${formatBytes(d.size)} · ${escapeHtml(d.modelLabel)}</small></div><button data-id="${d.id}">×</button></div>`).join(''):'<p class="status">Biblioteka jest pusta.</p>'}
async function search(e){e.preventDefault();const q=$('#query').value.trim();if(!q)return;const chunks=await listChunks();if(!chunks.length)return toast('Najpierw dodaj dokumenty.');let vector=null,mode='słowa kluczowe';try{await ensure();[vector]=await engine.embed(q,'query');mode=engine.backend.toUpperCase()}catch{}const ranked=rankChunks(chunks.map(c=>({...c,vector:vector&&c.modelKey===$('#model').value?c.vector:null})),vector,q);$('#results').classList.remove('empty');$('#results').innerHTML=ranked.length?ranked.map((r,i)=>`<article class="result"><header><b>${i+1}. ${escapeHtml(r.docName)}</b><small>fragment ${r.chunkIndex+1} · ${mode}</small></header><p>${escapeHtml(r.text)}</p></article>`).join(''):'Brak dopasowań.'}
const demo=[['Oszczędzanie energii.md','Obniżenie temperatury o jeden stopień ogranicza zapotrzebowanie na ciepło. W taryfie dwustrefowej warto przesuwać podgrzewanie wody na tańsze godziny.'],['Plan serwisowy.csv','Kontrola paska osprzętu co 15000 km. Objawy: piski lub postrzępione krawędzie. Olej silnikowy należy wymieniać co 10000 km.'],['LocalFind.txt','Celem jest przeszukiwanie prywatnych dokumentów bez chmury. WebNN żąda NPU, a WebGPU i WASM są fallbackiem.']];
$('#files').onchange=e=>addFiles([...e.target.files]);$('#drop').ondragover=e=>e.preventDefault();$('#drop').ondrop=e=>{e.preventDefault();addFiles([...e.dataTransfer.files])};$('#add-note').onclick=()=>addText($('#note-name').value||'Notatka.txt',$('#note').value).then(()=>{$('#note').value=''}).catch(e=>toast(e.message));$('#demo').onclick=async()=>{for(const[n,t]of demo)try{await addText(n,t,t.length)}catch{}toast('Dane demo gotowe.')};$('#search').onsubmit=search;$('#start').onclick=()=>ensure().catch(e=>toast(e.message));$('#library').onclick=async e=>{const b=e.target.closest('button[data-id]');if(b){await removeDocument(b.dataset.id);refresh()}};$('#clear').onclick=async()=>{if(confirm('Usunąć całą lokalną bibliotekę?')){await clearAll();refresh()}};
const caps=engine.capabilities();$('#hardware').textContent=caps.webnn?'WebNN dostępne — uruchom silnik':caps.webgpu?'NPU nieaktywne · WebGPU dostępne':'NPU nieaktywne · CPU / WASM';$('#diagnostics').onclick=()=>{$('#diag').innerHTML=`<p><b>WebNN API:</b> ${caps.webnn?'tak':'nie'}</p><p><b>WebGPU:</b> ${caps.webgpu?'tak':'nie'}</p><p><b>Bezpieczny kontekst:</b> ${caps.secure?'tak':'nie'}</p><p><b>Aktualny backend:</b> ${engine.backend?engine.backend.toUpperCase():'silnik nieuruchomiony'}</p>${caps.webnn?'<p>WebNN jest dostępne. Wybierz „Tylko NPU” i uruchom silnik, aby zweryfikować NPU.</p>':'<p><b>NPU nie jest teraz używane.</b> Aplikacja wybierze WebGPU lub CPU. Otwórz instrukcję „Jak uruchomić NPU?”.</p>'}`;$('#dialog').showModal()};$('#close').onclick=()=>$('#dialog').close();
const showNpuHelp=()=>$('#npu-dialog').showModal();$('#npu-help').onclick=showNpuHelp;$('#npu-help-engine').onclick=showNpuHelp;$('#npu-close').onclick=()=>$('#npu-dialog').close();$('#copy-flag').onclick=async()=>{try{await navigator.clipboard.writeText('chrome://flags/#web-machine-learning-neural-network');toast('Adres flagi skopiowany.')}catch{toast('Skopiuj adres ręcznie z instrukcji.')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});refresh();