import{rankChunks,escapeHtml}from'./search-core.js';import{reviewContract}from'./contract-review.js';import{sourceLabel}from'./document-locations.js';

export function isRiskQuestion(query,lang='pl'){const value=String(query??'').toLowerCase();return lang==='pl'?/(pułapk|ryzyk|niebezpiecz|uważać|problematycz|niekorzystn)/.test(value):/(trap|risk|danger|watch out|unfavourable|unfavorable|problematic)/.test(value)}

function compact(text,max=260){const value=String(text??'').replace(/\s+/g,' ').trim();return value.length>max?`${value.slice(0,max-1).trim()}…`:value}

export function buildRiskAnswer(chunks,lang='pl'){const results=reviewContract(chunks,lang).filter(result=>result.status!=='missing'&&result.findings.length);const items=results.map(result=>{const source=result.findings[0];return{title:result.check.title,explanation:result.check.why,source,location:sourceLabel(source,lang),quote:compact(source.text,420)}});const intro=lang==='pl'?`Znalazłem ${items.length} obszarów, które warto sprawdzić przed podpisaniem.`:`I found ${items.length} areas worth checking before signing.`;return{kind:'risks',intro,items}}

export function buildQuestionAnswer(query,chunks,lang='pl',queryVector=null){const ranked=rankChunks(chunks,queryVector,query,3);if(!ranked.length)return{kind:'answer',intro:lang==='pl'?'Nie znalazłem w dokumentach jednoznacznej odpowiedzi. Spróbuj doprecyzować pytanie.':'I could not find a clear answer in the documents. Try making the question more specific.',items:[]};const first=ranked[0];const intro=lang==='pl'?`Najbardziej pasujący zapis mówi: ${compact(first.text,220)}`:`The most relevant clause says: ${compact(first.text,220)}`;return{kind:'answer',intro,items:ranked.map(source=>({title:source.docName,explanation:lang==='pl'?'To źródło najlepiej odpowiada na pytanie.':'This source best matches the question.',source,location:sourceLabel(source,lang),quote:compact(source.text,420)}))}}

export function renderConversationAnswer(answer,lang='pl'){const sourceText=lang==='pl'?'Pokaż fragment źródłowy':'Show source passage';const locationText=lang==='pl'?'Źródło':'Source';return`<div class="assistant-answer"><p class="answer-intro">${escapeHtml(answer.intro)}</p>${answer.items.length?`<ol class="answer-points">${answer.items.map(item=>`<li><h4>${escapeHtml(item.title)}</h4><p>${escapeHtml(item.explanation)}</p><div class="source-ref"><b>${locationText}:</b> ${escapeHtml(item.source.docName)} · ${escapeHtml(item.location)}</div><details><summary>${sourceText}</summary><blockquote>${escapeHtml(item.quote)}</blockquote></details></li>`).join('')}</ol>`:''}</div>`}
