export const CUSTOM_RULES_STORAGE_KEY='localsafe-custom-rules-v1';
const MAX_NAME=80,MAX_PATTERN=500,MAX_MASK=80;
const TEXT={
 pl:{title:'Własne reguły',intro:'Dodaj własny tekst lub RegExp, który ma być wykrywany i zastępowany wybraną maską.',name:'Nazwa reguły',namePlaceholder:'np. Numer klienta',mode:'Tryb',literal:'Tekst dokładny',regex:'Wyrażenie regularne',pattern:'Wzorzec',literalPlaceholder:'np. PROJEKT-ALFA',regexPlaceholder:'np. \\bKLIENT-\\d{6}\\b',mask:'Maska',ignoreCase:'Ignoruj wielkość liter',add:'Dodaj regułę',remove:'Usuń',enabled:'Włączona',disabled:'Wyłączona',empty:'Nie dodano jeszcze własnych reguł.',note:'Reguły są zapisywane wyłącznie lokalnie w tej przeglądarce. Złożone regexy mogą spowolnić analizę.',invalidName:'Podaj nazwę reguły.',invalidPattern:'Podaj wzorzec.',invalidRegex:'Nieprawidłowe wyrażenie regularne.',emptyMatch:'Wzorzec nie może dopasowywać pustego tekstu.',storageError:'Nie udało się zapisać reguł w pamięci przeglądarki.'},
 en:{title:'Custom rules',intro:'Add your own text or regular expression to detect and replace with a chosen mask.',name:'Rule name',namePlaceholder:'e.g. Customer number',mode:'Mode',literal:'Exact text',regex:'Regular expression',pattern:'Pattern',literalPlaceholder:'e.g. PROJECT-ALPHA',regexPlaceholder:'e.g. \\bCUSTOMER-\\d{6}\\b',mask:'Mask',ignoreCase:'Ignore letter case',add:'Add rule',remove:'Remove',enabled:'Enabled',disabled:'Disabled',empty:'No custom rules have been added yet.',note:'Rules are stored only in this browser. Complex regular expressions may slow down analysis.',invalidName:'Enter a rule name.',invalidPattern:'Enter a pattern.',invalidRegex:'Invalid regular expression.',emptyMatch:'The pattern cannot match empty text.',storageError:'Could not save rules in browser storage.'}
};
function copy(value){return JSON.parse(JSON.stringify(value))}
function escapeRegExp(value){return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function lineColumn(text,index){const before=text.slice(0,index),lines=before.split('\n');return{line:lines.length,column:lines.at(-1).length+1}}
function languageText(lang){return TEXT[lang]||TEXT.en}
export function normalizeCustomRule(input={},index=0){return{id:String(input.id||`rule-${index+1}`),name:String(input.name||'').trim().slice(0,MAX_NAME),mode:input.mode==='literal'?'literal':'regex',pattern:String(input.pattern||'').trim().slice(0,MAX_PATTERN),mask:String(input.mask||'[CUSTOM]').trim().slice(0,MAX_MASK)||'[CUSTOM]',ignoreCase:input.ignoreCase!==false,enabled:input.enabled!==false}}
export function validateCustomRule(input,lang='pl'){
 const text=languageText(lang),rule=normalizeCustomRule(input);
 if(!rule.name)return{valid:false,rule,error:text.invalidName};
 if(!rule.pattern)return{valid:false,rule,error:text.invalidPattern};
 const source=rule.mode==='literal'?escapeRegExp(rule.pattern):rule.pattern,flags=`gu${rule.ignoreCase?'i':''}`;
 let regex;try{regex=new RegExp(source,flags)}catch(error){return{valid:false,rule,error:`${text.invalidRegex} ${error.message}`}}
 regex.lastIndex=0;if(regex.test(''))return{valid:false,rule,error:text.emptyMatch};regex.lastIndex=0;
 return{valid:true,rule,regex,error:null};
}
export function scanCustomRules(text,rules=[],lang='pl'){
 const input=String(text??''),findings=[],errors=[];
 for(const raw of Array.isArray(rules)?rules:[]){const checked=validateCustomRule(raw,lang),rule=checked.rule;if(!rule.enabled)continue;if(!checked.valid){errors.push({id:rule.id,name:rule.name,error:checked.error});continue}const regex=checked.regex;let match;while((match=regex.exec(input))){const value=match[0];if(!value.length){regex.lastIndex++;continue}const location=lineColumn(input,match.index);findings.push({type:'custom',value,start:match.index,end:match.index+value.length,...location,mask:rule.mask,risk:'high',source:'custom-rule',customRuleId:rule.id,customRuleName:rule.name,customRuleMode:rule.mode});}}
 return{findings:findings.sort((a,b)=>a.start-b.start||a.end-b.end),errors};
}
export function loadCustomRules(storage){try{const target=storage??globalThis.localStorage;if(!target)return[];const parsed=JSON.parse(target.getItem(CUSTOM_RULES_STORAGE_KEY)||'[]');return(Array.isArray(parsed)?parsed:[]).map(normalizeCustomRule)}catch{return[]}}
export function saveCustomRules(rules,storage){try{const target=storage??globalThis.localStorage;if(!target)return false;target.setItem(CUSTOM_RULES_STORAGE_KEY,JSON.stringify((Array.isArray(rules)?rules:[]).map(normalizeCustomRule)));return true}catch{return false}}
function makeId(){return globalThis.crypto?.randomUUID?.()||`rule-${Date.now()}-${Math.random().toString(36).slice(2)}`}
export function createCustomRulesController({getLang=()=> 'pl',storage,root=globalThis.document,onChange=()=>{}}={}){
 const element=id=>root?.getElementById?.(id),form=element('custom-rule-form'),list=element('custom-rules-list'),error=element('custom-rule-error');
 let rules=loadCustomRules(storage);
 function showError(message=''){if(!error)return;error.textContent=message;error.hidden=!message}
 function persist(){if(!saveCustomRules(rules,storage))showError(languageText(getLang()).storageError)}
 function render(){if(!list)return;const text=languageText(getLang());list.replaceChildren();if(!rules.length){const empty=root.createElement('p');empty.className='empty-state custom-rule-empty';empty.textContent=text.empty;list.append(empty);return}for(const rule of rules){const item=root.createElement('article');item.className='custom-rule-item';const toggle=root.createElement('label');toggle.className='custom-rule-toggle';const checkbox=root.createElement('input');checkbox.type='checkbox';checkbox.checked=rule.enabled;checkbox.setAttribute('aria-label',`${rule.name}: ${rule.enabled?text.enabled:text.disabled}`);checkbox.onchange=()=>{rule.enabled=checkbox.checked;persist();render();onChange(copy(rules))};const state=root.createElement('span');state.textContent=rule.enabled?text.enabled:text.disabled;toggle.append(checkbox,state);const body=root.createElement('div');body.className='custom-rule-body';const name=root.createElement('b');name.textContent=rule.name;const code=root.createElement('code');code.textContent=rule.mode==='regex'?`/${rule.pattern}/gu${rule.ignoreCase?'i':''}`:`“${rule.pattern}”`;const replacement=root.createElement('small');replacement.textContent=`→ ${rule.mask}`;body.append(name,code,replacement);const remove=root.createElement('button');remove.type='button';remove.className='link custom-rule-remove';remove.textContent=text.remove;remove.onclick=()=>{rules=rules.filter(item=>item.id!==rule.id);persist();render();onChange(copy(rules))};item.append(toggle,body,remove);list.append(item)}}
 function applyLanguage(){const text=languageText(getLang()),bindings={customRulesTitle:'title',customRulesIntro:'intro',customRuleNameLabel:'name',customRuleModeLabel:'mode',customRulePatternLabel:'pattern',customRuleMaskLabel:'mask',customRuleIgnoreLabel:'ignoreCase',customRuleAdd:'add',customRulesNote:'note'};for(const[id,key]of Object.entries(bindings)){const node=element(id);if(node)node.textContent=text[key]}const mode=element('custom-rule-mode');if(mode){mode.options[0].textContent=text.literal;mode.options[1].textContent=text.regex}const name=element('custom-rule-name'),pattern=element('custom-rule-pattern');if(name)name.placeholder=text.namePlaceholder;if(pattern)pattern.placeholder=mode?.value==='regex'?text.regexPlaceholder:text.literalPlaceholder;render()}
 if(form){const mode=element('custom-rule-mode'),pattern=element('custom-rule-pattern');mode.onchange=()=>{pattern.placeholder=mode.value==='regex'?languageText(getLang()).regexPlaceholder:languageText(getLang()).literalPlaceholder};form.onsubmit=event=>{event.preventDefault();showError();const candidate={id:makeId(),name:element('custom-rule-name').value,mode:mode.value,pattern:pattern.value,mask:element('custom-rule-mask').value,ignoreCase:element('custom-rule-ignore').checked,enabled:true},checked=validateCustomRule(candidate,getLang());if(!checked.valid){showError(checked.error);return}rules.push(checked.rule);persist();form.reset();element('custom-rule-mask').value='[CUSTOM]';element('custom-rule-ignore').checked=true;mode.value='literal';pattern.placeholder=languageText(getLang()).literalPlaceholder;render();onChange(copy(rules))}}
 applyLanguage();
 return{getRules:()=>copy(rules),applyLanguage,render};
}