import{applyMaskAlpha,clamp,computeMaskBounds,coverRect,filenameForDownload,MODEL_SIZE,scaleDimensions}from'./editor-core.js';
import{SegmentationEngine}from'./editor-runtime.js';
const $=s=>document.querySelector(s),sample='https://images.pexels.com/photos/5965592/pexels-photo-5965592.jpeg?auto=compress&cs=tinysrgb&w=1600';
const s={bitmap:null,bgBitmap:null,name:'image',rotation:0,flipX:false,flipY:false,maxEdge:1400,brightness:100,contrast:100,saturation:100,sepia:0,grayscale:0,blur:0,bgMode:'original',bgA:'#f6f7fb',bgB:'#dbe8ff',bgBlur:18,outline:0,shadow:0,mask:null,bounds:null,redactionMode:'off',redactionIntensity:16,redactions:[],format:'png',quality:92,result:null,drawing:null};
const r={file:$('#file-input'),bgFile:$('#background-input'),browse:$('#browse-button'),sample:$('#sample-button'),drop:$('#dropzone'),meta:$('#file-meta'),init:$('#init-button'),segment:$('#segment-button'),cv:$('#preset-cv'),sticker:$('#preset-sticker'),portraitBlur:$('#preset-blur'),backend:$('#backend-select'),status:$('#engine-status'),cap:$('#capability-badge'),runtime:$('#runtime-badge'),progress:$('#model-progress'),bar:$('#progress-bar'),progressText:$('#progress-text'),before:$('#original-canvas'),after:$('#result-canvas'),overlay:$('#overlay-canvas'),beforeEmpty:$('#original-empty'),afterEmpty:$('#result-empty'),maskBadge:$('#mask-badge'),download:$('#download-button'),downloadStatus:$('#download-status'),reset:$('#reset-button'),format:$('#export-format'),quality:$('#export-quality'),qualityOut:$('#quality-output'),bgMode:$('#background-mode'),bgA:$('#bg-color-a'),bgB:$('#bg-color-b'),bgBlur:$('#bg-blur'),bgBlurOut:$('#bg-blur-output'),outline:$('#outline-width'),shadow:$('#shadow-strength'),redactionMode:$('#redaction-mode'),redactionIntensity:$('#redaction-intensity'),redactionOut:$('#redaction-intensity-output'),undo:$('#undo-redaction'),clear:$('#clear-redactions'),left:$('#rotate-left'),right:$('#rotate-right'),flipX:$('#flip-x'),flipY:$('#flip-y'),maxEdge:$('#max-edge'),maxEdgeOut:$('#max-edge-output'),fit:$('#fit-view'),recipes:[...document.querySelectorAll('.recipe-button')]};
const controls={brightness:$('#brightness'),contrast:$('#contrast'),saturation:$('#saturation'),sepia:$('#sepia'),grayscale:$('#grayscale'),blur:$('#blur')},outs={brightness:$('#brightness-output'),contrast:$('#contrast-output'),saturation:$('#saturation-output'),sepia:$('#sepia-output'),grayscale:$('#grayscale-output'),blur:$('#blur-output')};
const bctx=r.before.getContext('2d'),actx=r.after.getContext('2d'),octx=r.overlay.getContext('2d'),maskCanvas=document.createElement('canvas');maskCanvas.width=maskCanvas.height=MODEL_SIZE;
const engine=new SegmentationEngine({status:m=>r.status.textContent=m,progress:e=>progress(e)});
function badge(el,text,tone='neutral'){el.textContent=text;el.dataset.tone=tone}
function progress(e){if(!e){r.progress.hidden=true;r.bar.style.width='0%';return}r.progress.hidden=false;const p=Number.isFinite(e.progress)?Math.max(0,Math.min(100,e.progress)):0;r.bar.style.width=`${p}%`;r.progressText.textContent=`${e.label||'Model'} · ${Math.round(p)}%`}
function capabilities(){const c=engine.capabilities();c.webnn?badge(r.cap,'WebNN dostępne','success'):c.webgpu?badge(r.cap,'Brak WebNN · jest WebGPU','warning'):badge(r.cap,'Fallback CPU / WASM','warning')}
function canvasSize(w,h){for(const c of[r.before,r.after,r.overlay]){c.width=w;c.height=h;c.style.width='100%'}}
function outputs(){for(const k in controls)outs[k].textContent=`${s[k]}${k==='blur'?' px':'%'}`;r.maxEdgeOut.textContent=`${s.maxEdge} px`;r.bgBlurOut.textContent=`${s.bgBlur} px`;r.redactionOut.textContent=s.redactionIntensity;r.qualityOut.textContent=`${s.quality}%`}
function sync(){for(const k in controls)controls[k].value=s[k];r.maxEdge.value=s.maxEdge;r.bgMode.value=s.bgMode;r.bgA.value=s.bgA;r.bgB.value=s.bgB;r.bgBlur.value=s.bgBlur;r.outline.value=s.outline;r.shadow.value=s.shadow;r.redactionMode.value=s.redactionMode;r.redactionIntensity.value=s.redactionIntensity;r.format.value=s.format;r.quality.value=s.quality;outputs()}
function defaults(){Object.assign(s,{rotation:0,flipX:false,flipY:false,maxEdge:1400,brightness:100,contrast:100,saturation:100,sepia:0,grayscale:0,blur:0,bgMode:'original',bgA:'#f6f7fb',bgB:'#dbe8ff',bgBlur:18,outline:0,shadow:0,mask:null,bounds:null,redactionMode:'off',redactionIntensity:16,redactions:[],format:'png',quality:92,drawing:null});sync()}
async function load(blob,name='image.jpg'){if(blob.size>20*1024*1024)throw Error('Plik przekracza limit 20 MB.');if(!/^image\/(jpeg|png|webp)$/i.test(blob.type))throw Error('Wybierz plik JPG, PNG lub WebP.');s.bitmap?.close?.();s.bitmap=await createImageBitmap(blob,{imageOrientation:'from-image'});s.name=name;defaults();const d=scaleDimensions(s.bitmap.width,s.bitmap.height,s.maxEdge);canvasSize(d.width,d.height);r.beforeEmpty.hidden=true;r.afterEmpty.hidden=false;for(const el of[r.segment,r.cv,r.sticker,r.portraitBlur,r.reset,r.download])el.disabled=false;r.meta.textContent=`${name} · ${s.bitmap.width}×${s.bitmap.height} · ${(blob.size/1048576).toFixed(1)} MB`;r.downloadStatus.textContent='Obraz gotowy do edycji.';render()}
async function loadBg(blob){if(!/^image\/(jpeg|png|webp)$/i.test(blob.type))throw Error('Obraz tła musi być JPG, PNG lub WebP.');s.bgBitmap?.close?.();s.bgBitmap=await createImageBitmap(blob,{imageOrientation:'from-image'});render()}
function base(){if(!s.bitmap)return null;const swap=Math.abs(s.rotation%180)===90,w0=swap?s.bitmap.height:s.bitmap.width,h0=swap?s.bitmap.width:s.bitmap.height,{width:w,height:h,scale}=scaleDimensions(w0,h0,s.maxEdge),c=document.createElement('canvas'),x=c.getContext('2d');c.width=w;c.height=h;x.save();x.translate(w/2,h/2);x.rotate(s.rotation*Math.PI/180);x.scale(s.flipX?-1:1,s.flipY?-1:1);x.drawImage(s.bitmap,-s.bitmap.width*scale/2,-s.bitmap.height*scale/2,s.bitmap.width*scale,s.bitmap.height*scale);x.restore();return c}
function adjusted(c){const o=document.createElement('canvas'),x=o.getContext('2d');o.width=c.width;o.height=c.height;x.filter=`brightness(${s.brightness}%) contrast(${s.contrast}%) saturate(${s.saturation}%) sepia(${s.sepia}%) grayscale(${s.grayscale}%) blur(${s.blur}px)`;x.drawImage(c,0,0);return o}
function upscale(m,w,h){const x=maskCanvas.getContext('2d'),img=x.createImageData(MODEL_SIZE,MODEL_SIZE);for(let i=0;i<m.length;i++){const v=Math.round(clamp(m[i])*255),o=i*4;img.data[o]=img.data[o+1]=img.data[o+2]=v;img.data[o+3]=255}x.putImageData(img,0,0);const c=document.createElement('canvas'),cx=c.getContext('2d',{willReadFrequently:true});c.width=w;c.height=h;cx.imageSmoothingEnabled=true;cx.imageSmoothingQuality='high';cx.drawImage(maskCanvas,0,0,w,h);const d=cx.getImageData(0,0,w,h).data,out=new Float32Array(w*h);for(let i=0;i<out.length;i++)out[i]=d[i*4]/255;return out}
function foreground(src){const x=src.getContext('2d',{willReadFrequently:true}),img=x.getImageData(0,0,src.width,src.height),c=document.createElement('canvas');c.width=src.width;c.height=src.height;c.getContext('2d').putImageData(new ImageData(applyMaskAlpha(img.data,s.mask),c.width,c.height),0,0);return c}
function silhouette(color='#fff'){const c=document.createElement('canvas'),x=c.getContext('2d'),img=x.createImageData(r.after.width,r.after.height),hex=color.replace('#',''),v=parseInt(hex,16),rgb=[v>>16&255,v>>8&255,v&255];c.width=r.after.width;c.height=r.after.height;for(let i=0;i<s.mask.length;i++){const o=i*4;img.data[o]=rgb[0];img.data[o+1]=rgb[1];img.data[o+2]=rgb[2];img.data[o+3]=s.mask[i]>=.5?255:0}x.putImageData(img,0,0);return c}
function background(x,w,h,src){if(s.bgMode==='solid'){x.fillStyle=s.bgA;x.fillRect(0,0,w,h)}else if(s.bgMode==='gradient'){const g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,s.bgA);g.addColorStop(1,s.bgB);x.fillStyle=g;x.fillRect(0,0,w,h)}else if(s.bgMode==='blur'){x.save();x.filter=`blur(${s.bgBlur}px)`;x.drawImage(src,-s.bgBlur,-s.bgBlur,w+s.bgBlur*2,h+s.bgBlur*2);x.restore()}else if(s.bgMode==='image'&&s.bgBitmap){const q=coverRect(s.bgBitmap.width,s.bgBitmap.height,w,h);x.drawImage(s.bgBitmap,q.x,q.y,q.width,q.height)}else if(s.bgMode==='image'){x.fillStyle=s.bgA;x.fillRect(0,0,w,h)}else if(s.bgMode==='original')x.drawImage(src,0,0)}
function redact(c){const x=c.getContext('2d');for(const a of s.redactions){const px=Math.round(Math.min(a.x,a.x+a.w)),py=Math.round(Math.min(a.y,a.y+a.h)),w=Math.round(Math.abs(a.w)),h=Math.round(Math.abs(a.h));if(!w||!h)continue;if(a.mode==='black'){x.fillStyle='#000';x.fillRect(px,py,w,h)}else if(a.mode==='blur'){const t=document.createElement('canvas'),tx=t.getContext('2d');t.width=w;t.height=h;tx.filter=`blur(${a.n}px)`;tx.drawImage(c,px,py,w,h,0,0,w,h);x.drawImage(t,px,py)}else{const t=document.createElement('canvas'),tw=Math.max(1,Math.round(w/Math.max(2,a.n))),th=Math.max(1,Math.round(h/Math.max(2,a.n)));t.width=tw;t.height=th;t.getContext('2d').drawImage(c,px,py,w,h,0,0,tw,th);x.save();x.imageSmoothingEnabled=false;x.drawImage(t,0,0,tw,th,px,py,w,h);x.restore()}}}
function compose(src){const c=document.createElement('canvas'),x=c.getContext('2d');c.width=src.width;c.height=src.height;if(s.mask&&s.bgMode!=='original'){background(x,c.width,c.height,src);if(s.shadow>0){x.save();x.globalAlpha=.18;x.filter=`blur(${s.shadow}px)`;x.drawImage(silhouette('#000'),s.shadow/4,s.shadow/3);x.restore()}if(s.outline>0){const q=silhouette('#fff');for(let a=0;a<Math.PI*2;a+=Math.PI/12)x.drawImage(q,Math.cos(a)*s.outline,Math.sin(a)*s.outline)}x.drawImage(foreground(src),0,0)}else x.drawImage(src,0,0);redact(c);return c}
function overlay(){octx.clearRect(0,0,r.overlay.width,r.overlay.height);octx.save();octx.lineWidth=2;octx.setLineDash([8,6]);for(const a of s.redactions){octx.strokeStyle=a.mode==='black'?'#ff6f7d':a.mode==='pixelate'?'#8eb8ff':'#4fd4a2';octx.strokeRect(a.x,a.y,a.w,a.h)}if(s.drawing){octx.strokeStyle='#fff';octx.strokeRect(s.drawing.x,s.drawing.y,s.drawing.w,s.drawing.h)}octx.restore()}
function maskBadge(){s.mask?badge(r.maskBadge,`Maska AI: gotowa${s.bounds?` · obiekt ${(s.bounds.coverage*100).toFixed(0)}% kadru`:''}`,'success'):badge(r.maskBadge,'Maska AI: nieaktywna')}
function render(){actx.clearRect(0,0,r.after.width,r.after.height);if(!s.bitmap){s.result=null;overlay();maskBadge();return}const c=base(),a=adjusted(c);if(r.after.width!==a.width||r.after.height!==a.height)canvasSize(a.width,a.height);bctx.clearRect(0,0,a.width,a.height);bctx.drawImage(c,0,0);r.afterEmpty.hidden=true;s.result=compose(a);actx.drawImage(s.result,0,0);overlay();maskBadge()}
async function init(){r.init.disabled=true;try{progress({label:'Start',progress:0});const b=await engine.initialize(r.backend.value),label=b==='npu'?'NPU / WebNN':b==='webgpu'?'GPU / Transformers.js':'CPU / Transformers.js';badge(r.runtime,label,b==='npu'?'success':'warning');r.status.textContent=`${label} gotowy.`}catch(e){badge(r.runtime,'Błąd inicjalizacji','danger');r.status.textContent=e.message||String(e)}finally{r.init.disabled=false;progress(null)}}
async function segment(){if(!s.bitmap)return;r.segment.disabled=true;try{const c=base();if(!engine.backend)await init();if(!engine.backend)throw Error('Silnik nie został uruchomiony.');progress({label:'Analiza obrazu',progress:5});const t=performance.now(),m=await engine.run(c);s.mask=upscale(m,c.width,c.height);s.bounds=computeMaskBounds(s.mask,c.width,c.height,.45);r.status.textContent=`Maska gotowa · ${Math.round(performance.now()-t)} ms · ${engine.backend.toUpperCase()} · ${engine.runtimeLabel}`;render()}catch(e){r.status.textContent=e.message||String(e)}finally{r.segment.disabled=false;progress(null)}}
async function recipe(name){if(!s.bitmap)return;if(name==='privacy'){s.redactionMode='blur';r.redactionMode.value='blur';r.downloadStatus.textContent='Narysuj prostokąty na podglądzie wyniku.';return}if(!s.mask)await segment();if(!s.mask)return;if(name==='cv')Object.assign(s,{bgMode:'solid',bgA:'#f1f4f8',brightness:104,contrast:108,saturation:102,outline:0,shadow:0,format:'jpeg'});if(name==='sticker')Object.assign(s,{bgMode:'transparent',outline:8,shadow:10,format:'png'});if(name==='blur')Object.assign(s,{bgMode:'blur',bgBlur:22,outline:0,shadow:0,format:'jpeg'});sync();render()}
function point(e){const q=r.overlay.getBoundingClientRect();return{x:(e.clientX-q.left)*r.overlay.width/q.width,y:(e.clientY-q.top)*r.overlay.height/q.height}}
function download(){if(!s.result)return;const mime=s.format==='jpeg'?'image/jpeg':s.format==='webp'?'image/webp':'image/png';s.result.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filenameForDownload(s.name,s.format==='jpeg'?'jpg':s.format);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);r.downloadStatus.textContent='Plik został pobrany.'},mime,s.quality/100)}
for(const k in controls)controls[k].addEventListener('input',()=>{s[k]=Number(controls[k].value);outputs();render()});
r.browse.onclick=()=>r.file.click();r.file.onchange=e=>e.target.files[0]&&load(e.target.files[0],e.target.files[0].name).catch(x=>r.meta.textContent=x.message);r.bgFile.onchange=e=>e.target.files[0]&&loadBg(e.target.files[0]).catch(x=>r.downloadStatus.textContent=x.message);r.sample.onclick=async()=>{try{r.meta.textContent='Pobieranie przykładu…';const q=await fetch(sample,{mode:'cors',cache:'force-cache'});if(!q.ok)throw Error(`Example HTTP ${q.status}`);await load(await q.blob(),'example-portrait.jpg')}catch(e){r.meta.textContent=e.message}};
r.drop.ondragover=e=>{e.preventDefault();r.drop.classList.add('dragging')};r.drop.ondragleave=()=>r.drop.classList.remove('dragging');r.drop.ondrop=e=>{e.preventDefault();r.drop.classList.remove('dragging');const f=e.dataTransfer.files[0];f&&load(f,f.name).catch(x=>r.meta.textContent=x.message)};r.drop.onclick=e=>e.target.tagName!=='BUTTON'&&r.file.click();
r.init.onclick=init;r.segment.onclick=segment;r.cv.onclick=()=>recipe('cv');r.sticker.onclick=()=>recipe('sticker');r.portraitBlur.onclick=()=>recipe('blur');r.recipes.forEach(b=>b.onclick=()=>recipe(b.dataset.recipe));
for(const[id,delta]of[[r.left,-90],[r.right,90]])id.onclick=()=>{s.rotation=(s.rotation+delta+360)%360;s.mask=s.bounds=null;render()};r.flipX.onclick=()=>{s.flipX=!s.flipX;s.mask=s.bounds=null;render()};r.flipY.onclick=()=>{s.flipY=!s.flipY;s.mask=s.bounds=null;render()};r.maxEdge.oninput=()=>{s.maxEdge=Number(r.maxEdge.value);s.mask=s.bounds=null;outputs();render()};
r.bgMode.onchange=()=>{s.bgMode=r.bgMode.value;render()};r.bgA.oninput=()=>{s.bgA=r.bgA.value;render()};r.bgB.oninput=()=>{s.bgB=r.bgB.value;render()};r.bgBlur.oninput=()=>{s.bgBlur=Number(r.bgBlur.value);outputs();render()};r.outline.oninput=()=>{s.outline=Number(r.outline.value);render()};r.shadow.oninput=()=>{s.shadow=Number(r.shadow.value);render()};
r.redactionMode.onchange=()=>s.redactionMode=r.redactionMode.value;r.redactionIntensity.oninput=()=>{s.redactionIntensity=Number(r.redactionIntensity.value);outputs()};r.undo.onclick=()=>{s.redactions.pop();render()};r.clear.onclick=()=>{s.redactions=[];render()};
r.overlay.onpointerdown=e=>{if(!s.bitmap||s.redactionMode==='off')return;const p=point(e);s.drawing={x:p.x,y:p.y,w:0,h:0};overlay()};r.overlay.onpointermove=e=>{if(!s.drawing)return;const p=point(e);s.drawing.w=p.x-s.drawing.x;s.drawing.h=p.y-s.drawing.y;overlay()};r.overlay.onpointerup=()=>{if(!s.drawing)return;if(Math.abs(s.drawing.w)>6&&Math.abs(s.drawing.h)>6)s.redactions.push({...s.drawing,mode:s.redactionMode,n:s.redactionIntensity});s.drawing=null;render()};
r.format.onchange=()=>s.format=r.format.value;r.quality.oninput=()=>{s.quality=Number(r.quality.value);outputs()};r.download.onclick=download;r.reset.onclick=()=>{defaults();render()};r.fit.onclick=()=>r.after.closest('.canvas-card')?.scrollIntoView({behavior:'smooth',block:'center'});
capabilities();sync();maskBadge();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{}));
