import{MODEL_CONFIGS,normalizeVector}from'./search-core.js';
import{prepareModelInputSpecs}from'./model-feeds.js';
const TF='https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0/+esm';
async function fetchWithProgress(url,onProgress=()=>{}){const response=await fetch(url);if(!response.ok)throw Error(`Model HTTP ${response.status}`);const total=Number(response.headers.get('content-length'))||0;if(!response.body){const buffer=await response.arrayBuffer();onProgress({stage:'model',loaded:buffer.byteLength,total:buffer.byteLength,progress:100});return new Uint8Array(buffer)}const reader=response.body.getReader(),chunks=[];let loaded=0;for(;;){const{done,value}=await reader.read();if(done)break;chunks.push(value);loaded+=value.byteLength;onProgress({stage:'model',loaded,total,progress:total?loaded/total*100:null})}const data=new Uint8Array(loaded);let offset=0;for(const chunk of chunks){data.set(chunk,offset);offset+=chunk.byteLength}onProgress({stage:'model',loaded,total:total||loaded,progress:100});return data}
export class EmbeddingEngine{
 constructor(status=()=>{},progress=()=>{}){this.status=status;this.progress=progress;this.session=null;this.tokenizer=null;this.backend=null;this.preference=null;this.modelKey=null}
 capabilities(){return{secure:isSecureContext,webnn:Boolean(navigator.ml?.createContext),webgpu:Boolean(navigator.gpu),wasm:Boolean(WebAssembly)}}
 async dispose(){if(this.session?.release)await this.session.release();this.session=null;this.tokenizer=null;this.backend=null;this.preference=null;this.modelKey=null}
 async initialize(modelKey='multilingual',preference='auto'){
  const cfg=MODEL_CONFIGS[modelKey];if(!cfg)throw Error(`Nieznany model: ${modelKey}`);if(!globalThis.ort)throw Error('ONNX Runtime Web nie został załadowany.');if(this.session)await this.dispose();
  this.status('Pobieranie tokenizera…');this.progress({stage:'tokenizer',progress:null,loaded:0,total:0});const{AutoTokenizer}=await import(TF);this.tokenizer=await AutoTokenizer.from_pretrained(cfg.modelId,{progress_callback:event=>{const loaded=Number(event.loaded)||0,total=Number(event.total)||0;this.progress({stage:'tokenizer',file:event.file||event.name||'',loaded,total,progress:Number.isFinite(event.progress)?event.progress:total?loaded/total*100:null})}});this.progress({stage:'tokenizer',progress:100});
  this.status('Pobieranie modelu ONNX…');const model=await fetchWithProgress(cfg.modelUrl,event=>this.progress(event));
  const candidates=preference==='npu'?['npu']:preference==='gpu'?['webgpu']:preference==='cpu'?['wasm']:[...(navigator.ml?.createContext?['npu']:[]),...(navigator.gpu?['webgpu']:[]),'wasm'];
  const errors=[];for(const backend of candidates){try{this.status(`Tworzenie sesji ${backend.toUpperCase()}…`);this.progress({stage:'session',backend,progress:null});const providers=backend==='npu'?[{name:'webnn',deviceType:'npu',powerPreference:'low-power'}]:backend==='webgpu'?['webgpu']:['wasm'];this.session=await ort.InferenceSession.create(model,{executionProviders:providers,graphOptimizationLevel:'all'});this.backend=backend;this.preference=preference;this.modelKey=modelKey;this.progress({stage:'ready',backend,progress:100});return backend}catch(e){errors.push(`${backend}: ${e.message}`)}}throw Error(errors.join(' | '))
 }
 async embed(texts,kind='passage'){
  const cfg=MODEL_CONFIGS[this.modelKey],list=(Array.isArray(texts)?texts:[texts]).map(t=>(kind==='query'?cfg.queryPrefix:cfg.passagePrefix)+t);const encoded=await this.tokenizer(list,{padding:true,truncation:true,max_length:cfg.maxLength});const specs=prepareModelInputSpecs(encoded,this.session.inputNames),feeds={};for(const[name,spec]of Object.entries(specs))feeds[name]=new ort.Tensor('int64',spec.data,spec.dims);const outputs=await this.session.run(feeds);const out=Object.values(outputs).find(t=>t.dims.length===2)||Object.values(outputs).find(t=>t.dims.length===3)||Object.values(outputs)[0];if(out.dims.length===2){const[b,d]=out.dims;return Array.from({length:b},(_,i)=>normalizeVector(out.data.slice(i*d,(i+1)*d)))}const[b,s,d]=out.dims,mask=specs.attention_mask?.data,result=[];for(let row=0;row<b;row++){const v=new Float32Array(d);let n=0;for(let token=0;token<s;token++){if(mask&&!Number(mask[row*s+token]))continue;n++;const o=(row*s+token)*d;for(let i=0;i<d;i++)v[i]+=Number(out.data[o+i])}for(let i=0;i<d;i++)v[i]/=n||1;result.push(normalizeVector(v))}return result
 }
}