import{escapeHtml}from'./search-core.js';import{detectLanguage,setLanguage}from'./i18n.js';import{buildLocatedChunks}from'./document-locations.js';import{buildRiskAnswer,renderConversationAnswer}from'./conversation-answer.js';
const $=s=>document.querySelector(s);const texts={pl:{title:'Przykład rozmowy z umową',intro:'Kliknij pytanie. Odpowiedź powstanie z tego dokumentu i wskaże konkretne linie.',doc:'Dokument testowy',test:'Rozmowa',run:'Jakie są pułapki w umowie?',runTop:'Uruchom przykład',welcome:'Zapytaj o pułapki w widocznej umowie.',method:'Co jest naprawdę testowane?',methodCopy:'Przykład używa tego samego modułu odpowiedzi co główna aplikacja. Test przechodzi tylko wtedy, gdy odpowiedź ma osiem ryzyk, osiem źródeł oraz poprawne numery linii.',pass:'TEST ZALICZONY',fail:'TEST NIEZALICZONY'},en:{title:'Example conversation with a contract',intro:'Click the question. The answer is built from this document and cites exact lines.',doc:'Test document',test:'Conversation',run:'What are the traps in this contract?',runTop:'Run example',welcome:'Ask about traps in the visible contract.',method:'What is actually tested?',methodCopy:'The example uses the same answer module as the main app. It passes only when the answer contains eight risks, eight sources and valid line numbers.',pass:'TEST PASSED',fail:'TEST FAILED'}};
const contracts={pl:`UMOWA ABONAMENTOWA
1. Umowa zostaje zawarta na 12 miesięcy i automatycznie przedłuża się na kolejny okres 12 miesięcy, jeżeli klient nie złoży wypowiedzenia.
2. Wypowiedzenie wymaga formy pisemnej i trzymiesięcznego okresu wypowiedzenia.
3. Miesięczna opłata wynosi 129 zł. Usługodawca może raz w roku podwyższyć cenę zgodnie z inflacją.
4. Za rozwiązanie umowy przed końcem okresu klient zapłaci karę umowną 600 zł.
5. Usługodawca nie odpowiada za utracone korzyści, a jego odpowiedzialność jest ograniczona do trzech miesięcznych opłat.
6. Klient musi zgłosić zmianę adresu w terminie 7 dni.
7. Dane osobowe są przetwarzane w celu realizacji umowy; zgoda marketingowa jest dobrowolna.
8. Spory rozstrzyga sąd właściwy dla siedziby usługodawcy, a prawem właściwym jest prawo polskie.`,en:`SUBSCRIPTION AGREEMENT
1. This agreement is for 12 months and automatically renews for another 12-month period unless the customer gives notice.
2. Termination requires written notice and a three-month notice period.
3. The monthly fee is $39. The provider may increase the price once per year based on inflation.
4. Early termination triggers a contractual penalty of $200.
5. The provider is not liable for lost profits and limits liability to three monthly fees.
6. The customer must notify an address change within 7 days.
7. Personal data is processed to perform the agreement; marketing consent is optional.
8. Disputes are subject to the courts at the provider's registered office and the governing law is Polish law.`};
let lang=setLanguage(detectLanguage());function chunks(){return buildLocatedChunks(contracts[lang],{maxChars:180}).map((chunk,i)=>({id:String(i),docName:texts[lang].doc,...chunk,vector:null}))}function apply(next){lang=setLanguage(next);$('#language').value=lang;const t=texts[lang];$('#example-title').textContent=t.title;$('#example-intro').textContent=t.intro;$('#document-title').textContent=t.doc;$('#test-title').textContent=t.test;$('#run-example').textContent=t.run;$('#run-example-top').textContent=t.runTop;$('#example-welcome').textContent=t.welcome;$('#method-title').textContent=t.method;$('#method-copy').textContent=t.methodCopy;$('#contract-text').textContent=contracts[lang];$('#verification').hidden=true;$('#example-conversation').innerHTML=`<div class="message assistant"><div><b>ContractGuard</b><p>${escapeHtml(t.welcome)}</p></div></div>`}
function run(){const t=texts[lang],question=t.run,answer=buildRiskAnswer(chunks(),lang);$('#example-conversation').insertAdjacentHTML('beforeend',`<div class="message user"><div><p>${escapeHtml(question)}</p></div></div><div class="message assistant"><div><b>ContractGuard</b>${renderConversationAnswer(answer,lang)}</div></div>`);const valid=answer.items.length===8&&answer.items.every(item=>item.source&&Number.isFinite(item.source.lineStart)&&item.location.includes(String(item.source.lineStart)));$('#verification').hidden=false;$('#verification').className=`verification ${valid?'pass':'fail'}`;$('#verification').innerHTML=`<b>${valid?t.pass:t.fail}</b><span>${answer.items.length}/8</span>`}
$('#language').onchange=e=>apply(e.target.value);$('#run-example').onclick=run;$('#run-example-top').onclick=run;apply(lang);
