import{scanSensitiveData,redactSensitiveData,summarizeFindings,typeLabel}from'./privacy-scanner.js';import{detectLanguage,setLanguage}from'./i18n.js';
const $=s=>document.querySelector(s);let lang=setLanguage(detectLanguage()),findings=[];
const ui={pl:{title:'Sprawdź tekst przed wysłaniem.',intro:'Wklej wiadomość, log lub fragment dokumentu. LocalSafe wykryje dane wrażliwe i utworzy zanonimizowaną kopię — wszystko lokalnie.',scan:'Skanuj tekst',demo:'Wstaw bezpieczne demo',copy:'Kopiuj zanonimizowany tekst',clear:'Wyczyść',input:'Tekst do sprawdzenia',output:'Wersja do wysłania',results:'Wykryte dane',empty:'Nie znaleziono danych wrażliwych.',ready:'Wklej tekst i uruchom skanowanie.',line:'linia',column:'kolumna',copied:'Skopiowano.',contract:'Audyt umowy',example:'Przykład audytu',privacy:'Treść nie opuszcza tej karty przeglądarki.'},en:{title:'Check text before you send it.',intro:'Paste a message, log or document excerpt. LocalSafe detects sensitive data and creates a redacted copy — entirely on-device.',scan:'Scan text',demo:'Insert safe demo',copy:'Copy redacted text',clear:'Clear',input:'Text to inspect',output:'Safe-to-send version',results:'Detected data',empty:'No sensitive data found.',ready:'Paste text and run the scan.',line:'line',column:'column',copied:'Copied.',contract:'Contract review',example:'Review example',privacy:'The content never leaves this browser tab.'}};
function t(){return ui[lang]||ui.en}function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function applyLanguage(next){lang=setLanguage(next);$('#language').value=lang;const x=t();document.documentElement.lang=lang;document.title=lang==='pl'?'LocalSafe NPU — skaner prywatności':'LocalSafe NPU — privacy scanner';for(const [id,key]of Object.entries({pageTitle:'title',pageIntro:'intro',scan:'scan',demo:'demo',copy:'copy',clear:'clear',inputTitle:'input',outputTitle:'output',resultsTitle:'results',privacyNote:'privacy',contractLink:'contract',exampleLink:'example'}))$('#'+id).textContent=x[key];$('#scan-status').textContent=x.ready;render()}
function render(){const x=t(),container=$('#findings');if(!findings.length){container.innerHTML=`<p class="empty-state">${escapeHtml($('#source').value?x.empty:x.ready)}</p>`;$('#summary').hidden=true;return}const summary=summarizeFindings(findings);$('#summary').hidden=false;$('#summary').innerHTML=`<b>${findings.length}</b> ${lang==='pl'?'elementów do ukrycia':'items to redact'} · ${Object.keys(summary).length} ${lang==='pl'?'typów':'types'}`;container.innerHTML=findings.map(item=>`<article class="finding ${item.risk}"><div><small>${escapeHtml(typeLabel(item.type,lang))}</small><b>${escapeHtml(item.value)}</b><span>${x.line} ${item.line}, ${x.column} ${item.column}</span></div><strong>${item.risk==='critical'?'!':item.risk==='high'?'↑':'•'}</strong></article>`).join('')}
function scan(){const text=$('#source').value;findings=scanSensitiveData(text);$('#redacted').value=redactSensitiveData(text,findings);$('#scan-status').textContent=findings.length?(lang==='pl'?`Znaleziono ${findings.length} elementów.`:`Found ${findings.length} items.`):t().empty;render()}
const demoPL=`Cześć, proszę wysłać fakturę do anna.kowalska@example.com.\nPESEL klienta: 44051401458. Telefon: +48 501 234 567.\nRachunek: PL61 1090 1014 0000 0712 1981 2874.\nKarta testowa: 4111 1111 1111 1111.\nSerwer: 192.168.1.25.\nToken testowy: sk-demoOnly1234567890ABCDEF`;
const demoEN=`Please send the invoice to anna.kowalska@example.com.\nCustomer ID: 44051401458. Phone: +48 501 234 567.\nAccount: PL61 1090 1014 0000 0712 1981 2874.\nTest card: 4111 1111 1111 1111.\nServer: 192.168.1.25.\nTest token: sk-demoOnly1234567890ABCDEF`;
$('#language').onchange=e=>applyLanguage(e.target.value);$('#scan').onclick=scan;$('#demo').onclick=()=>{$('#source').value=lang==='pl'?demoPL:demoEN;scan()};$('#clear').onclick=()=>{$('#source').value='';$('#redacted').value='';findings=[];$('#scan-status').textContent=t().ready;render()};$('#copy').onclick=async()=>{if(!$('#redacted').value)return;try{await navigator.clipboard.writeText($('#redacted').value);$('#scan-status').textContent=t().copied}catch{$('#redacted').select();document.execCommand('copy')}};$('#source').addEventListener('input',()=>{$('#scan-status').textContent=t().ready});applyLanguage(lang);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
