import{scanSensitiveData,typeLabel,BUILT_IN_VALIDATED_RULES}from'./privacy-scanner.js';
import{EmbeddingEngine}from'./embedding-engine.js';
import{classifySensitiveText,categoryLabel}from'./sensitivity-engine.js';
import{extractSemanticSpans,selectRedactionSpans,BUILT_IN_SEMANTIC_RULES}from'./semantic-spans.js';
import{detectLanguage,setLanguage}from'./i18n.js';
import{MODEL_CONFIGS}from'./search-core.js';
import{createCustomRulesController,scanCustomRules}from'./custom-rules.js';

const $=selector=>document.querySelector(selector);
const BUILT_IN_RULE_COUNT=BUILT_IN_VALIDATED_RULES.length+BUILT_IN_SEMANTIC_RULES.length;
let lang=setLanguage(detectLanguage()),findings=[];
const formatBytes=value=>value?`${(value/1024/1024).toFixed(1)} MB`:'—',MODEL_KEY='localsafe-model',BACKEND_KEY='localsafe-backend';
const ui={
 pl:{title:'Sprawdź, czy tekst zawiera poufne informacje.',intro:'Wybrany model analizuje znaczenie każdego zdania lokalnie.',scan:'Uruchom analizę AI',demo:'Wstaw demo',copy:'Kopiuj',clear:'Wyczyść',input:'Tekst do analizy',output:'Wersja do wysłania',rules:'Reguły anonimizacji',results:'Wyniki analizy',ready:'Model nieuruchomiony.',empty:'Nie wykryto poufnej treści.',line:'linia',copied:'Skopiowano.',contract:'Audyt umowy',example:'Przykład audytu',privacy:'Treść nie jest wysyłana do serwera. Model pobierany jest do przeglądarki.',model:'Model AI',backend:'Akcelerator',rulesChanged:'Reguły zmienione. Uruchom analizę ponownie.',builtInTitle:'Reguły wbudowane',builtInIntro:'Aktywne reguły używane przez skaner. Można je przeglądać, ale nie zmieniać ani wyłączać.',readOnly:'Tylko odczyt',validatedGroup:'Walidowane formaty',semanticGroup:'NPU + ekstrakcja zakresu',builtIn:'Wbudowana',format:'Format',validation:'Walidacja',validatedSource:'Reguła deterministyczna',semanticSource:'Kontekst NPU'},
 en:{title:'Check whether text contains confidential information.',intro:'The selected model analyzes each sentence locally.',scan:'Run AI analysis',demo:'Insert demo',copy:'Copy',clear:'Clear',input:'Text to analyze',output:'Safe-to-send version',rules:'Redaction rules',results:'Analysis results',ready:'Model not started.',empty:'No confidential content detected.',line:'line',copied:'Copied.',contract:'Contract review',example:'Review example',privacy:'Text is not sent to a server. The model is downloaded into the browser.',model:'AI model',backend:'Accelerator',rulesChanged:'Rules changed. Run the analysis again.',builtInTitle:'Built-in rules',builtInIntro:'Active rules used by the scanner. They can be inspected but not edited or disabled.',readOnly:'Read only',validatedGroup:'Validated formats',semanticGroup:'NPU + precise span extraction',builtIn:'Built-in',format:'Format',validation:'Validation',validatedSource:'Deterministic rule',semanticSource:'NPU context'}
};
function t(){return ui[lang]||ui.en}
function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function selectedModel(){return MODEL_CONFIGS[$('#model').value]||MODEL_CONFIGS.multilingual}
function renderModelInfo(){const config=selectedModel();$('#model-description').textContent=`${config.description} · ${config.download}`}
function renderBuiltInRules(){
 const list=$('#builtin-rules-list');if(!list)return;const text=t();list.replaceChildren();
 $('#builtinRulesReadOnly').textContent=`${text.readOnly} · ${BUILT_IN_RULE_COUNT}`;
 const groups=[{title:text.validatedGroup,rules:BUILT_IN_VALIDATED_RULES,source:text.validatedSource},{title:text.semanticGroup,rules:BUILT_IN_SEMANTIC_RULES,source:text.semanticSource}];
 for(const group of groups){const section=document.createElement('section');section.className='builtin-rule-group';const heading=document.createElement('h4');heading.textContent=`${group.title} (${group.rules.length})`;const grid=document.createElement('div');grid.className='builtin-rule-grid';for(const rule of group.rules){const item=document.createElement('article');item.className=`builtin-rule-item ${rule.risk||'high'}`;item.setAttribute('aria-readonly','true');const head=document.createElement('div');head.className='builtin-rule-head';const name=document.createElement('b');name.textContent=rule[lang]||rule.en;const badge=document.createElement('span');badge.className='builtin-rule-badge';badge.textContent=text.builtIn;head.append(name,badge);const description=document.createElement('p');description.textContent=rule.format?.[lang]||rule.format?.en||'';const metadata=document.createElement('div');metadata.className='builtin-rule-meta';const mask=document.createElement('code');mask.textContent=rule.mask;const validation=document.createElement('small');validation.textContent=`${text.validation}: ${rule.validation?.[lang]||rule.validation?.en||group.source}`;const source=document.createElement('small');source.textContent=group.source;metadata.append(mask,validation,source);item.append(head,description,metadata);grid.append(item)}section.append(heading,grid);list.append(section)}
}
function progress(event){const panel=$('#download-panel'),bar=$('#download-progress'),percent=$('#download-percent'),detail=$('#download-detail'),bytes=$('#download-bytes'),stage=$('#download-stage');panel.hidden=false;const labels={pl:{tokenizer:'Pobieranie tokenizera',model:'Pobieranie modelu ONNX',session:'Tworzenie sesji WebNN',ready:'Model gotowy'},en:{tokenizer:'Downloading tokenizer',model:'Downloading ONNX model',session:'Creating WebNN session',ready:'Model ready'}}[lang]||{};stage.textContent=labels[event.stage]||event.stage||'';detail.textContent=event.file||event.backend?.toUpperCase()||'';bytes.textContent=event.total?`${formatBytes(event.loaded)} / ${formatBytes(event.total)}`:formatBytes(event.loaded);if(event.progress==null){bar.removeAttribute('value');percent.textContent='…'}else{const value=Math.max(0,Math.min(100,event.progress));bar.value=value;percent.textContent=`${Math.round(value)}%`}if(event.stage==='ready')setTimeout(()=>panel.hidden=true,1300)}
const engine=new EmbeddingEngine(message=>{$('#scan-status').textContent=message},progress);
const customRules=createCustomRulesController({getLang:()=>lang,onChange:()=>{$('#scan-status').textContent=t().rulesChanged}});
function applyLanguage(next){lang=setLanguage(next);$('#language').value=lang;const text=t();document.documentElement.lang=lang;document.title=lang==='pl'?'LocalSafe NPU — analiza poufnej treści':'LocalSafe NPU — confidential content analysis';for(const[id,key]of Object.entries({pageTitle:'title',pageIntro:'intro',scan:'scan',demo:'demo',copy:'copy',clear:'clear',inputTitle:'input',outputTitle:'output',rulesTitle:'rules',resultsTitle:'results',privacyNote:'privacy',contractLink:'contract',exampleLink:'example',modelLabel:'model',backendLabel:'backend',builtinRulesTitle:'builtInTitle',builtinRulesIntro:'builtInIntro'}))$('#'+id).textContent=text[key];customRules.applyLanguage();renderBuiltInRules();if(!engine.session)$('#scan-status').textContent=text.ready;renderModelInfo();render()}
function redact(text,items){let output=text;for(const item of selectRedactionSpans(items).sort((a,b)=>b.start-a.start))output=output.slice(0,item.start)+(item.mask||'[SENSITIVE]')+output.slice(item.end);return output}
function render(){const text=t(),container=$('#findings');if(!findings.length){container.innerHTML=`<p class="empty-state">${escapeHtml($('#source').value?text.empty:text.ready)}</p>`;$('#summary').hidden=true;return}const semantic=findings.filter(item=>item.source==='semantic-model').length,spans=findings.filter(item=>item.source==='semantic-span').length,rules=findings.filter(item=>item.source==='validated-rule').length,custom=findings.filter(item=>item.source==='custom-rule').length;$('#summary').hidden=false;$('#summary').innerHTML=`<b>${findings.length}</b> ${lang==='pl'?'wyników':'findings'} · ${semantic} ${lang==='pl'?'ostrzeżeń NPU':'NPU warnings'} · ${spans} ${lang==='pl'?'zakresów':'spans'} · ${rules} ${lang==='pl'?'reguł wbudowanych':'built-in rules'} · ${custom} ${lang==='pl'?'reguł własnych':'custom rules'}`;container.innerHTML=findings.map(item=>{let label,source,icon;if(item.source==='semantic-model'){label=categoryLabel(item.type,lang);source=`${engine.backend?.toUpperCase()||'AI'} · ${selectedModel().label} · ${(item.score*100).toFixed(0)}% · ${lang==='pl'?'ostrzeżenie, bez wycinania':'warning, not redacted'}`;icon='AI'}else if(item.source==='semantic-span'){label=lang==='pl'?`Zakres: ${item.type}`:`Span: ${item.type}`;source=`${engine.backend?.toUpperCase()||'AI'} · ${lang==='pl'?'ekstrakcja zakresu':'span extraction'}`;icon='⌖'}else if(item.source==='custom-rule'){label=item.customRuleName;source=lang==='pl'?`Własna reguła · ${item.customRuleMode==='regex'?'RegExp':'tekst dokładny'}`:`Custom rule · ${item.customRuleMode==='regex'?'RegExp':'exact text'}`;icon='R'}else{label=typeLabel(item.type,lang);source=lang==='pl'?'Reguła + walidacja':'Rule + validation';icon='✓'}return`<article class="finding ${item.risk||'high'}"><div><small>${escapeHtml(label)}</small><b>${escapeHtml(item.value)}</b><span>${text.line} ${item.line} · ${escapeHtml(source)}</span></div><strong>${icon}</strong></article>`}).join('')}
async function scan(){const text=$('#source').value.trim();if(!text)return;$('#scan').disabled=true;try{const preference=$('#backend').value,modelKey=$('#model').value;if(!engine.session||engine.modelKey!==modelKey||engine.preference!==preference)await engine.initialize(modelKey,preference);const config=selectedModel();$('#hardware').textContent=`${engine.backend.toUpperCase()} · ${config.label}`;const started=performance.now(),semantic=await classifySensitiveText(text,engine,lang),spans=extractSemanticSpans(text,semantic),rules=scanSensitiveData(text).map(item=>({...item,source:'validated-rule'})),custom=scanCustomRules(text,customRules.getRules(),lang);findings=[...semantic,...spans,...rules,...custom.findings].sort((a,b)=>a.start-b.start||a.end-b.end);$('#redacted').value=redact(text,findings);const elapsed=Math.round(performance.now()-started),skipped=custom.errors.length?` · ${custom.errors.length} ${lang==='pl'?'błędnych reguł pominięto':'invalid rules skipped'}`:'';$('#scan-status').textContent=lang==='pl'?`Gotowe: ${findings.length} wyników · ${elapsed} ms · ${config.label} · ${engine.backend.toUpperCase()}${skipped}`:`Done: ${findings.length} findings · ${elapsed} ms · ${config.label} · ${engine.backend.toUpperCase()}${skipped}`;progress({stage:'ready',backend:engine.backend,progress:100});render()}catch(error){$('#scan-status').textContent=error.message;$('#hardware').textContent='AI unavailable';$('#download-panel').hidden=true}finally{$('#scan').disabled=false}}
const demoPL=`Jan Kowalski mieszka w Poznaniu przy ulicy Długiej 12. Lekarz rozpoznał nadciśnienie i zalecił codzienne leczenie. Zalecił brać rutinoscorbin. Wynagrodzenie pracownika wynosi 12 500 zł brutto. PESEL klienta: 44051401458. E-mail: jan.kowalski@example.com. Token testowy: sk-demoOnly1234567890ABCDEF`,demoEN=`John Smith lives at 12 Long Street in London. The doctor diagnosed hypertension and prescribed daily treatment. The employee salary is $4,200 per month. Email: john.smith@example.com. Test token: sk-demoOnly1234567890ABCDEF`;
for(const config of Object.values(MODEL_CONFIGS)){const option=document.createElement('option');option.value=config.key;option.textContent=`${config.label} — ${config.download}`;$('#model').append(option)}
$('#model').value=MODEL_CONFIGS[localStorage.getItem(MODEL_KEY)]?localStorage.getItem(MODEL_KEY):'multilingual';
$('#backend').value=['npu','auto','gpu','cpu'].includes(localStorage.getItem(BACKEND_KEY))?localStorage.getItem(BACKEND_KEY):'npu';
renderModelInfo();
const capabilities=engine.capabilities();$('#hardware').textContent=capabilities.webnn?'WebNN available':capabilities.webgpu?'WebGPU available':'CPU only';
$('#model').onchange=async event=>{localStorage.setItem(MODEL_KEY,event.target.value);renderModelInfo();await engine.dispose();$('#scan-status').textContent=t().ready};
$('#backend').onchange=async event=>{localStorage.setItem(BACKEND_KEY,event.target.value);await engine.dispose();$('#scan-status').textContent=t().ready};
$('#language').onchange=event=>applyLanguage(event.target.value);
$('#scan').onclick=scan;
$('#demo').onclick=()=>{$('#source').value=lang==='pl'?demoPL:demoEN};
$('#clear').onclick=()=>{$('#source').value='';$('#redacted').value='';findings=[];render()};
$('#copy').onclick=async()=>{if(!$('#redacted').value)return;await navigator.clipboard.writeText($('#redacted').value);$('#scan-status').textContent=t().copied};
$('#npu-help').onclick=()=>$('#npu-dialog').showModal();
$('#npu-close').onclick=()=>$('#npu-dialog').close();
applyLanguage(lang);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});