import{MODEL_SIZE,MODEL_VARIANTS,rgbaToNchw,applyMaskAlpha,backendCandidates,scaledDimensions,outputFilename,clamp}from'./image-core.js';
const $=selector=>document.querySelector(selector),EXAMPLE_URL='https://images.pexels.com/photos/5965592/pexels-photo-5965592.jpeg?auto=compress&cs=tinysrgb&w=1200',LANG_KEY='locallab-language',BACKEND_KEY='portraitlab-backend';
const text={
 pl:{language:'Język',heroTitle:'Usuń albo zmień tło zdjęcia bez wysyłania go do chmury.',heroIntro:'Model MODNet wycina osobę lokalnie. Przygotuj zdjęcie do CV, profilu, ogłoszenia lub miniatury i pobierz wynik jako PNG albo JPEG.',example:'Wczytaj przykład',pick:'Wybierz zdjęcie',privacy:'Zdjęcie pozostaje w pamięci tej karty. Pobierany jest wyłącznie model AI.',how1Title:'1. Dodaj portret',how1Copy:'Przeciągnij JPG, PNG lub WebP. Przycisk „Wczytaj przykład” uruchamia ten sam proces na gotowym zdjęciu.',how2Title:'2. Wytnij osobę',how2Copy:'Wybierz NPU, tryb automatyczny, GPU lub CPU i uruchom model. Pierwsze użycie pobierze około 7–26 MB.',how3Title:'3. Ustaw tło i pobierz',how3Copy:'Wybierz przezroczystość, kolor albo rozmycie. Dopasuj krawędzie i zapisz PNG lub JPEG.',exampleTitle:'Przykład: zdjęcie profilowe do CV',exampleCopy:'Wczytaj przykład, uruchom AI, wybierz jasne tło i pobierz JPEG. Do logo, naklejki lub grafiki użyj przezroczystego PNG.',runExample:'Uruchom przykład',source:'Zdjęcie źródłowe',drop:'Przeciągnij zdjęcie lub kliknij',dropCopy:'JPG, PNG, WebP · maks. 20 MB',none:'Nie wybrano zdjęcia.',engine:'Silnik AI',backend:'Akcelerator',run:'Wytnij osobę',initial:'Dodaj zdjęcie, aby rozpocząć.',edit:'Tło i krawędzie',mode:'Tryb tła',transparent:'Przezroczyste',color:'Kolor',blur:'Rozmycie',original:'Oryginalne',colorLabel:'Kolor tła',blurLabel:'Siła rozmycia',threshold:'Próg maski',softness:'Miękkość krawędzi',download:'Pobierz wynik',downloadHelp:'PNG zachowuje przezroczystość. JPEG użyje białego tła, jeśli wybrano tryb przezroczysty.',preview:'Porównanie przed i po',previewCopy:'Podgląd aktualizuje się bez ponownego uruchamiania modelu.',reset:'Resetuj ustawienia',before:'Przed',after:'Po',beforeEmpty:'Tutaj pojawi się oryginalne zdjęcie.',afterEmpty:'Po uruchomieniu AI zobaczysz gotowy wynik.',localTitle:'Wszystko lokalnie',localCopy:'Piksele zdjęcia nie są wysyłane do Hugging Face ani do serwera strony. Model jest pobierany niezależnie i działa w przeglądarce.',feature1:'Przezroczyste PNG',feature1Copy:'Do logo, naklejki, miniatury i dalszej obróbki.',feature2:'Profesjonalne tło',feature2Copy:'Jednolity kolor do CV albo rozmycie zachowujące kontekst zdjęcia.',feature3:'Jawny backend',feature3Copy:'Widzisz, czy model rzeczywiście działa na NPU, WebGPU czy CPU/WASM.',loadingExample:'Pobieranie zdjęcia przykładowego…',loadingModel:'Pobieranie modelu…',creating:'Tworzenie sesji',running:'Analiza portretu…',ready:'Gotowe',fileTooLarge:'Plik przekracza limit 20 MB.',badFile:'Wybierz plik JPG, PNG albo WebP.',noBackend:'Wybrany akcelerator nie jest dostępny w tej przeglądarce.',downloaded:'Plik został przygotowany.',exampleCredit:'Przykład z Pexels',backendAuto:'NPU → GPU → CPU',backendNpu:'Tylko NPU',backendGpu:'GPU',backendCpu:'CPU'},
 en:{language:'Language',heroTitle:'Remove or replace a photo background without uploading it to the cloud.',heroIntro:'MODNet cuts out a person locally. Prepare a CV photo, profile picture, listing or thumbnail and export PNG or JPEG.',example:'Load example',pick:'Choose photo',privacy:'The photo stays in this browser tab. Only the AI model is downloaded.',how1Title:'1. Add a portrait',how1Copy:'Drop a JPG, PNG or WebP. “Load example” runs the same workflow on a ready-made photo.',how2Title:'2. Cut out the person',how2Copy:'Choose NPU, automatic, GPU or CPU and run the model. First use downloads about 7–26 MB.',how3Title:'3. Set the background and export',how3Copy:'Choose transparency, color or blur. Refine edges and save PNG or JPEG.',exampleTitle:'Example: a CV profile photo',exampleCopy:'Load the example, run AI, select a light background and export JPEG. Use transparent PNG for stickers or further editing.',runExample:'Run example',source:'Source photo',drop:'Drop a photo or click',dropCopy:'JPG, PNG, WebP · max 20 MB',none:'No photo selected.',engine:'AI engine',backend:'Accelerator',run:'Cut out person',initial:'Add a photo to begin.',edit:'Background and edges',mode:'Background mode',transparent:'Transparent',color:'Color',blur:'Blur',original:'Original',colorLabel:'Background color',blurLabel:'Blur strength',threshold:'Mask threshold',softness:'Edge softness',download:'Download result',downloadHelp:'PNG preserves transparency. JPEG uses white when transparent mode is selected.',preview:'Before and after',previewCopy:'The preview updates without rerunning the model.',reset:'Reset settings',before:'Before',after:'After',beforeEmpty:'The original photo will appear here.',afterEmpty:'The finished result will appear after AI runs.',localTitle:'Everything stays local',localCopy:'Photo pixels are not sent to Hugging Face or the site server. The model is downloaded separately and runs in the browser.',feature1:'Transparent PNG',feature1Copy:'For logos, stickers, thumbnails and further editing.',feature2:'Professional background',feature2Copy:'A solid CV color or blur that preserves the context.',feature3:'Visible backend',feature3Copy:'See whether the model actually runs on NPU, WebGPU or CPU/WASM.',loadingExample:'Downloading example photo…',loadingModel:'Downloading model…',creating:'Creating session',running:'Analyzing portrait…',ready:'Done',fileTooLarge:'The file exceeds the 20 MB limit.',badFile:'Choose a JPG, PNG or WebP file.',noBackend:'The selected accelerator is unavailable in this browser.',downloaded:'The file is ready.',exampleCredit:'Example from Pexels',backendAuto:'NPU → GPU → CPU',backendNpu:'NPU only',backendGpu:'GPU',backendCpu:'CPU'}
};
let lang=(localStorage.getItem(LANG_KEY)||navigator.language||'pl').toLowerCase().startsWith('pl')?'pl':'en',bitmap=null,sourceName='portrait',sourcePixels=null,maskSmall=null,maskFull=null,renderFrame=0;
const before=$('#before'),after=$('#after'),beforeContext=before.getContext('2d',{willReadFrequently:true}),afterContext=after.getContext('2d'),maskCanvas=document.createElement('canvas'),maskFullCanvas=document.createElement('canvas'),foregroundCanvas=document.createElement('canvas');maskCanvas.width=maskCanvas.height=MODEL_SIZE;
const modelCache=new Map();
async function fetchModel(url,onProgress){if(modelCache.has(url))return modelCache.get(url);const response=await fetch(url,{cache:'force-cache'});if(!response.ok)throw Error(`Model HTTP ${response.status}`);const total=Number(response.headers.get('content-length'))||0;if(!response.body){const bytes=new Uint8Array(await response.arrayBuffer());onProgress(bytes.byteLength,bytes.byteLength);modelCache.set(url,bytes);return bytes}const reader=response.body.getReader(),chunks=[];let loaded=0;for(;;){const{done,value}=await reader.read();if(done)break;chunks.push(value);loaded+=value.byteLength;onProgress(loaded,total)}const bytes=new Uint8Array(loaded);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}modelCache.set(url,bytes);onProgress(loaded,total||loaded);return bytes}
class PortraitEngine{
 constructor(){this.session=null;this.backend=null;this.preference=null}
 capabilities(){return{webnn:Boolean(navigator.ml?.createContext),webgpu:Boolean(navigator.gpu),wasm:Boolean(globalThis.WebAssembly)}}
 async dispose(){if(this.session?.release)await this.session.release();this.session=null;this.backend=null;this.preference=null}
 async initialize(preference='auto'){
  if(!globalThis.ort)throw Error('ONNX Runtime Web unavailable.');if(this.session&&this.preference===preference)return this.backend;await this.dispose();const candidates=backendCandidates(preference,this.capabilities());if(!candidates.length)throw Error(text[lang].noBackend);const errors=[];
  for(const backend of candidates){try{const variant=MODEL_VARIANTS[backend];setStatus(`${text[lang].loadingModel} ${variant.label} · ${variant.download}`);showProgress(true);const model=await fetchModel(variant.url,(loaded,total)=>updateProgress(loaded,total));setStatus(`${text[lang].creating} ${backend.toUpperCase()}…`);$('#progress').removeAttribute('value');$('#progress-value').textContent='…';const providers=backend==='npu'?[{name:'webnn',deviceType:'npu',powerPreference:'low-power'}]:backend==='webgpu'?['webgpu']:['wasm'];this.session=await ort.InferenceSession.create(model,{executionProviders:providers,graphOptimizationLevel:'all',freeDimensionOverrides:{batch_size:1,num_channels:3,height:MODEL_SIZE,width:MODEL_SIZE}});this.backend=backend;this.preference=preference;showProgress(false);return backend}catch(error){errors.push(`${backend}: ${error.message}`)}}throw Error(errors.join(' | '))
 }
 async run(input){const tensor=new ort.Tensor('float32',input,[1,3,MODEL_SIZE,MODEL_SIZE]),outputs=await this.session.run({[this.session.inputNames[0]]:tensor}),output=outputs[this.session.outputNames[0]]||Object.values(outputs)[0];return Float32Array.from(output.data,value=>clamp(Number(value)))}
}
const engine=new PortraitEngine();
function t(){return text[lang]}
function setStatus(message){$('#status').textContent=message}
function showProgress(show){$('#model-progress').hidden=!show;if(!show){$('#progress').value=0;$('#progress-value').textContent='0%'}}
function updateProgress(loaded,total){const percent=total?Math.min(100,loaded/total*100):null;if(percent==null){$('#progress').removeAttribute('value');$('#progress-value').textContent='…'}else{$('#progress').value=percent;$('#progress-value').textContent=`${Math.round(percent)}%`}$('#progress-label').textContent=t().loadingModel}
function applyLanguage(next){lang=next==='en'?'en':'pl';localStorage.setItem(LANG_KEY,lang);document.documentElement.lang=lang;$('#language').value=lang;const c=t(),bindings={languageLabel:'language',heroTitle:'heroTitle',heroIntro:'heroIntro',example:'example',pickHero:'pick',privacyNote:'privacy',how1Title:'how1Title',how1Copy:'how1Copy',how2Title:'how2Title',how2Copy:'how2Copy',how3Title:'how3Title',how3Copy:'how3Copy',exampleTitle:'exampleTitle',exampleCopy:'exampleCopy',exampleInline:'runExample',sourceTitle:'source',dropTitle:'drop',dropCopy:'dropCopy',engineTitle:'engine',backendLabel:'backend',run:'run',editTitle:'edit',modeLabel:'mode',modeTransparent:'transparent',modeColor:'color',modeBlur:'blur',modeOriginal:'original',colorLabel:'colorLabel',blurLabel:'blurLabel',thresholdLabel:'threshold',softnessLabel:'softness',downloadTitle:'download',downloadHelp:'downloadHelp',previewTitle:'preview',previewCopy:'previewCopy',reset:'reset',beforeLabel:'before',afterLabel:'after',beforeEmpty:'beforeEmpty',afterEmpty:'afterEmpty',localTitle:'localTitle',localCopy:'localCopy',feature1Title:'feature1',feature1Copy:'feature1Copy',feature2Title:'feature2',feature2Copy:'feature2Copy',feature3Title:'feature3',feature3Copy:'feature3Copy'};for(const[id,key]of Object.entries(bindings)){const node=$('#'+id);if(node)node.textContent=c[key]}const options=$('#backend').options;options[0].textContent=c.backendNpu;options[1].textContent=c.backendAuto;options[2].textContent=c.backendGpu;options[3].textContent=c.backendCpu;document.title=lang==='pl'?'PortraitLab NPU — lokalne studio obrazu':'PortraitLab NPU — local image studio';if(!bitmap)$('#file-meta').textContent=c.none;if(!bitmap)setStatus(c.initial)}
function setCanvasSize(width,height){for(const canvas of[before,after,maskFullCanvas,foregroundCanvas]){canvas.width=width;canvas.height=height}}
async function loadBlob(blob,name='portrait.jpg'){
 if(blob.size>20*1024*1024)throw Error(t().fileTooLarge);if(!/^image\/(jpeg|png|webp)$/i.test(blob.type))throw Error(t().badFile);bitmap?.close?.();bitmap=await createImageBitmap(blob,{imageOrientation:'from-image'});sourceName=name;const size=scaledDimensions(bitmap.width,bitmap.height);setCanvasSize(size.width,size.height);beforeContext.clearRect(0,0,before.width,before.height);beforeContext.drawImage(bitmap,0,0,before.width,before.height);sourcePixels=beforeContext.getImageData(0,0,before.width,before.height);maskSmall=null;maskFull=null;afterContext.clearRect(0,0,after.width,after.height);$('#before-empty').hidden=true;$('#after-empty').hidden=false;$('#run').disabled=false;setResultEnabled(false);$('#file-meta').textContent=`${name} · ${bitmap.width}×${bitmap.height} · ${(blob.size/1024/1024).toFixed(1)} MB`;setStatus(t().run);scrollPreview()
}
function setResultEnabled(enabled){$('#mode-field').disabled=!enabled;$('#download-png').disabled=!enabled;$('#download-jpg').disabled=!enabled;$('#reset').disabled=!enabled;$('#after-empty').hidden=enabled}
function buildModelInput(){const canvas=document.createElement('canvas');canvas.width=canvas.height=MODEL_SIZE;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0,MODEL_SIZE,MODEL_SIZE);return rgbaToNchw(context.getImageData(0,0,MODEL_SIZE,MODEL_SIZE).data,MODEL_SIZE,MODEL_SIZE)}
function buildFullMask(){const image=maskCanvas.getContext('2d').createImageData(MODEL_SIZE,MODEL_SIZE);for(let index=0;index<MODEL_SIZE*MODEL_SIZE;index++){const value=Math.round(clamp(maskSmall[index])*255),offset=index*4;image.data[offset]=image.data[offset+1]=image.data[offset+2]=value;image.data[offset+3]=255}maskCanvas.getContext('2d').putImageData(image,0,0);const context=maskFullCanvas.getContext('2d',{willReadFrequently:true});context.clearRect(0,0,maskFullCanvas.width,maskFullCanvas.height);context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(maskCanvas,0,0,maskFullCanvas.width,maskFullCanvas.height);const data=context.getImageData(0,0,maskFullCanvas.width,maskFullCanvas.height).data;maskFull=new Float32Array(maskFullCanvas.width*maskFullCanvas.height);for(let index=0;index<maskFull.length;index++)maskFull[index]=data[index*4]/255}
async function runModel(){if(!bitmap)return;$('#run').disabled=true;try{const backend=await engine.initialize($('#backend').value);$('#hardware').textContent=backend==='npu'?'NPU active':backend==='webgpu'?'WebGPU active':'CPU / WASM';setStatus(t().running);const started=performance.now(),output=await engine.run(buildModelInput()),pixels=MODEL_SIZE*MODEL_SIZE;maskSmall=output.length===pixels?output:output.slice(Math.max(0,output.length-pixels));buildFullMask();setResultEnabled(true);renderOutput();setStatus(`${t().ready} · ${Math.round(performance.now()-started)} ms · ${backend.toUpperCase()}`)}catch(error){setStatus(error.message);showProgress(false)}finally{$('#run').disabled=false}}
function currentMode(){return(document.querySelector('input[name="mode"]:checked')||{}).value||'transparent'}
function renderOutput(){if(!sourcePixels||!maskFull)return;const threshold=Number($('#threshold').value)/100,softness=Number($('#softness').value)/100,foreground=applyMaskAlpha(sourcePixels.data,maskFull,{threshold,softness}),foregroundContext=foregroundCanvas.getContext('2d');foregroundContext.putImageData(new ImageData(foreground,foregroundCanvas.width,foregroundCanvas.height),0,0);afterContext.clearRect(0,0,after.width,after.height);const mode=currentMode();if(mode==='color'){afterContext.fillStyle=$('#color').value;afterContext.fillRect(0,0,after.width,after.height)}else if(mode==='blur'){const blur=Number($('#blur').value);afterContext.save();afterContext.filter=`blur(${blur}px)`;const pad=blur*2;afterContext.drawImage(before,-pad,-pad,after.width+pad*2,after.height+pad*2);afterContext.restore()}else if(mode==='original')afterContext.drawImage(before,0,0);afterContext.drawImage(foregroundCanvas,0,0)}
function scheduleRender(){cancelAnimationFrame(renderFrame);renderFrame=requestAnimationFrame(renderOutput)}
function resetSettings(){document.querySelector('input[name="mode"][value="transparent"]').checked=true;$('#color').value='#f2f4f7';$('#blur').value=18;$('#threshold').value=50;$('#softness').value=18;updateOutputs();renderOutput()}
function updateOutputs(){$('#blur-value').value=`${$('#blur').value} px`;$('#threshold-value').value=`${$('#threshold').value}%`;$('#softness-value').value=`${$('#softness').value}%`}
function scrollPreview(){if(matchMedia('(max-width: 980px)').matches)$('.preview-panel').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadExample(){try{setStatus(t().loadingExample);const response=await fetch(EXAMPLE_URL,{mode:'cors',cache:'force-cache'});if(!response.ok)throw Error(`Example HTTP ${response.status}`);await loadBlob(await response.blob(),lang==='pl'?'przyklad-portretu.jpg':'example-portrait.jpg');$('#file-meta').textContent+=` · ${t().exampleCredit}`;await runModel()}catch(error){setStatus(error.message)}}
function download(type){const transparent=currentMode()==='transparent',canvas=document.createElement('canvas');canvas.width=after.width;canvas.height=after.height;const context=canvas.getContext('2d');if(type==='jpeg'&&transparent){context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height)}context.drawImage(after,0,0);canvas.toBlob(blob=>{if(!blob)return;const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=outputFilename(sourceName,type==='jpeg'?'jpg':'png');link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);setStatus(t().downloaded)},type==='jpeg'?'image/jpeg':'image/png',.92)}
const caps=engine.capabilities();$('#hardware').textContent=caps.webnn?'WebNN available':caps.webgpu?'WebGPU available':'CPU / WASM';$('#backend').value=['npu','auto','gpu','cpu'].includes(localStorage.getItem(BACKEND_KEY))?localStorage.getItem(BACKEND_KEY):'auto';$('#language').onchange=event=>applyLanguage(event.target.value);$('#pick-hero').onclick=()=>$('#file').click();$('#drop').onclick=()=>$('#file').click();$('#file').onchange=event=>event.target.files[0]&&loadBlob(event.target.files[0],event.target.files[0].name).catch(error=>setStatus(error.message));$('#drop').ondragover=event=>{event.preventDefault();$('#drop').classList.add('dragging')};$('#drop').ondragleave=()=>$('#drop').classList.remove('dragging');$('#drop').ondrop=event=>{event.preventDefault();$('#drop').classList.remove('dragging');const file=event.dataTransfer.files[0];if(file)loadBlob(file,file.name).catch(error=>setStatus(error.message))};$('#backend').onchange=async event=>{localStorage.setItem(BACKEND_KEY,event.target.value);await engine.dispose();if(bitmap)setStatus(t().run)};$('#run').onclick=runModel;$('#example').onclick=loadExample;$('#example-inline').onclick=loadExample;document.querySelectorAll('input[name="mode"],#color,#blur,#threshold,#softness').forEach(control=>control.oninput=()=>{updateOutputs();scheduleRender()});$('#reset').onclick=resetSettings;$('#download-png').onclick=()=>download('png');$('#download-jpg').onclick=()=>download('jpeg');updateOutputs();applyLanguage(lang);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{});
