export function validatePesel(value){const digits=value.replace(/\D/g,'');if(!/^\d{11}$/.test(digits))return false;const weights=[1,3,7,9,1,3,7,9,1,3];const check=(10-weights.reduce((sum,weight,index)=>sum+weight*Number(digits[index]),0)%10)%10;return check===Number(digits[10])}
export function validateLuhn(value){const digits=value.replace(/\D/g,'');if(!/^\d{13,19}$/.test(digits))return false;let sum=0,alternate=false;for(let index=digits.length-1;index>=0;index--){let number=Number(digits[index]);if(alternate){number*=2;if(number>9)number-=9}sum+=number;alternate=!alternate}return sum%10===0}
export function validateIban(value){const iban=value.replace(/\s/g,'').toUpperCase();if(!/^[A-Z]{2}\d{2}[A-Z0-9]{11,30}$/.test(iban))return false;const moved=iban.slice(4)+iban.slice(0,4);let remainder=0;for(const character of moved){const expanded=/\d/.test(character)?character:String(character.charCodeAt(0)-55);for(const digit of expanded)remainder=(remainder*10+Number(digit))%97}return remainder===1}
function validIp(value){return value.split('.').every(part=>Number(part)>=0&&Number(part)<=255)}
function validPhone(value){return value.replace(/\D/g,'').length>=9}
function freezeRule(rule){return Object.freeze({...rule,format:Object.freeze(rule.format),validation:Object.freeze(rule.validation)})}
export const BUILT_IN_VALIDATED_RULES=Object.freeze([
 freezeRule({id:'apiKey',type:'apiKey',pl:'Klucz API / token',en:'API key / token',risk:'critical',mask:'[API_KEY]',engine:'validated',format:{pl:'Popularne tokeny OpenAI, GitHub, AWS, Google i Slack',en:'Common OpenAI, GitHub, AWS, Google and Slack tokens'},validation:{pl:'Prefiks dostawcy i minimalna długość',en:'Provider prefix and minimum length'},regex:/(?:sk-[A-Za-z0-9_-]{16,}|gh[pousr]_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{30,}|xox[baprs]-[A-Za-z0-9-]{10,})/g}),
 freezeRule({id:'pesel',type:'pesel',pl:'PESEL',en:'Polish national ID',risk:'critical',mask:'[PESEL]',engine:'validated',format:{pl:'11 kolejnych cyfr',en:'11 consecutive digits'},validation:{pl:'Suma kontrolna PESEL',en:'PESEL checksum'},regex:/\b\d{11}\b/g,validate:validatePesel}),
 freezeRule({id:'iban',type:'iban',pl:'Numer rachunku / IBAN',en:'Bank account / IBAN',risk:'high',mask:'[IBAN]',engine:'validated',format:{pl:'Kod kraju, cyfry kontrolne i numer rachunku',en:'Country code, check digits and account number'},validation:{pl:'Walidacja IBAN modulo 97',en:'IBAN modulo 97 validation'},regex:/\b(?:[A-Z]{2}\d{2}[ ]?(?:[A-Z0-9][ ]?){11,30})\b/g,validate:validateIban}),
 freezeRule({id:'card',type:'card',pl:'Karta płatnicza',en:'Payment card',risk:'critical',mask:'[CARD]',engine:'validated',format:{pl:'13–19 cyfr, opcjonalne spacje lub myślniki',en:'13–19 digits with optional spaces or dashes'},validation:{pl:'Algorytm Luhna',en:'Luhn algorithm'},regex:/(?<!\d)(?:\d[ -]?){13,19}(?!\d)/g,validate:validateLuhn}),
 freezeRule({id:'email',type:'email',pl:'Adres e-mail',en:'Email address',risk:'medium',mask:'[EMAIL]',engine:'validated',format:{pl:'Nazwa użytkownika, @, domena i końcówka',en:'Local part, @, domain and suffix'},validation:{pl:'Walidacja struktury adresu',en:'Address structure validation'},regex:/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi}),
 freezeRule({id:'ip',type:'ip',pl:'Adres IPv4',en:'IPv4 address',risk:'medium',mask:'[IP]',engine:'validated',format:{pl:'Cztery liczby oddzielone kropkami',en:'Four dot-separated numbers'},validation:{pl:'Każdy oktet w zakresie 0–255',en:'Every octet between 0 and 255'},regex:/(?<![\d.])(?:25[0-5]|2[0-4]\d|1?\d?\d)(?:\.(?:25[0-5]|2[0-4]\d|1?\d?\d)){3}(?![\d.])/g,validate:validIp}),
 freezeRule({id:'phone',type:'phone',pl:'Numer telefonu',en:'Phone number',risk:'medium',mask:'[PHONE]',engine:'validated',format:{pl:'9 cyfr, opcjonalny prefiks +48 i separatory',en:'9 digits with optional +48 prefix and separators'},validation:{pl:'Co najmniej 9 cyfr po usunięciu separatorów',en:'At least 9 digits after removing separators'},regex:/(?<!\w)(?:\+?48[ -]?)?(?:\d{3}[ -]?\d{3}[ -]?\d{3})(?!\w)/g,validate:validPhone})
]);
const TYPE_MAP=Object.freeze(Object.fromEntries(BUILT_IN_VALIDATED_RULES.map(rule=>[rule.type,rule])));
function lineColumn(text,index){const before=text.slice(0,index),lines=before.split('\n');return{line:lines.length,column:lines.at(-1).length+1}}
function collect(text,rule){const output=[],regex=rule.regex,validate=rule.validate||(()=>true);regex.lastIndex=0;for(const match of text.matchAll(regex)){const value=match[0];if(!validate(value))continue;const location=lineColumn(text,match.index);output.push({type:rule.type,value,start:match.index,end:match.index+value.length,...location,pl:rule.pl,en:rule.en,risk:rule.risk,mask:rule.mask})}return output}
export function scanSensitiveData(text){const input=String(text??''),candidates=BUILT_IN_VALIDATED_RULES.flatMap(rule=>collect(input,rule)).sort((a,b)=>a.start-b.start||b.end-a.end),accepted=[];for(const item of candidates){if(accepted.some(other=>item.start<other.end&&item.end>other.start))continue;accepted.push(item)}return accepted}
export function redactSensitiveData(text,findings=scanSensitiveData(text)){let output=String(text??'');for(const finding of [...findings].sort((a,b)=>b.start-a.start))output=output.slice(0,finding.start)+finding.mask+output.slice(finding.end);return output}
export function summarizeFindings(findings){return findings.reduce((summary,item)=>{summary[item.type]=(summary[item.type]||0)+1;return summary},{})}
export function typeLabel(type,lang='pl'){return TYPE_MAP[type]?.[lang]||type}