const ADDRESS_TYPE=String.raw`(?:ul(?:ica|icy|icą|\.)?|aleja|alei|aleją|al\.|plac|placu|osiedle|osiedla|osiedlu|os\.)`;
const STREET_NAME=String.raw`[A-ZĄĆĘŁŃÓŚŹŻ][\p{L}-]+(?:\s+[A-ZĄĆĘŁŃÓŚŹŻ][\p{L}-]+)*`;
const BUILDING=String.raw`\d+[A-Za-z]?(?:\/\d+[A-Za-z]?)?(?:\s+m\.?\s*\d+[A-Za-z]?)?`;
const APARTMENT_NUMBER=String.raw`\d+[A-Za-z]?(?:\/\d+[A-Za-z]?)?`;
const APARTMENT_SUFFIX=String.raw`(?:\s+(?:(?:w\s+)?mieszkaniu(?:\s+nr\.?)?|mieszkanie(?:\s+nr\.?)?|(?:w\s+)?lokalu(?:\s+nr\.?)?|lokal(?:\s+nr\.?)?|nr\.?\s+lokalu)\s+${APARTMENT_NUMBER})?`;
export const ADDRESS_RE=new RegExp(String.raw`\b${ADDRESS_TYPE}\s+${STREET_NAME}\s+${BUILDING}${APARTMENT_SUFFIX}\b`,'giu');
const ADDRESS_CANDIDATE_RE=new RegExp(String.raw`\b([\p{L}.]{2,12})\s+(${STREET_NAME})\s+(${BUILDING})\b`,'gu');
const APARTMENT_AFTER_RE=new RegExp(String.raw`^\s+(?:w\s+)?([\p{L}]{4,14})(?:\s+nr\.?)?\s+(${APARTMENT_NUMBER})\b`,'iu');
const APARTMENT_NR_RE=new RegExp(String.raw`^\s+nr\.?\s+([\p{L}]{4,14})\s+(${APARTMENT_NUMBER})\b`,'iu');
const ADDRESS_TYPE_WORDS=Object.freeze(['ul','al','os','ulica','ulicy','ulicą','aleja','alei','aleją','plac','placu','osiedle','osiedla','osiedlu']);
const APARTMENT_WORDS=Object.freeze(['mieszkaniu','mieszkanie','lokalu','lokal']);
const MEDICATION_PREFIX=String.raw`(?:lek(?:u|iem|i)?|tablet(?:ka|ki|kę|ek|kami)?|preparat(?:u|em)?|branie(?:\s+tabletki)?|(?:zalecił|zaleciła|kazał|kazała)\s+(?:brać|stosować|przyjmować|zażywać)|przepisał|przepisała|stosować|przyjmować|zażywać)`;
export const MEDICATION_RE=new RegExp(String.raw`\b${MEDICATION_PREFIX}\s+(?:lek(?:u)?\s+|tablet(?:kę|ki|ka)\s+|preparat\s+)?((?!leczenie\b|lek(?:i|u)?\b|tablet(?:ka|ki|kę)\b)[\p{L}][\p{L}\d-]{2,})\b`,'giu');
function normalizeKeyword(value){return String(value??'').toLocaleLowerCase('pl-PL').replace(/\.+$/,'')}
export function isWithinOneEdit(left,right){
 const a=normalizeKeyword(left),b=normalizeKeyword(right);if(a===b)return true;if(Math.abs(a.length-b.length)>1)return false;
 if(a.length===b.length){const mismatch=[];for(let i=0;i<a.length;i++)if(a[i]!==b[i])mismatch.push(i);if(mismatch.length===1)return true;if(mismatch.length!==2)return false;const[first,second]=mismatch;return second===first+1&&a[first]===b[second]&&a[second]===b[first]}
 const longer=a.length>b.length?a:b,shorter=a.length>b.length?b:a;let i=0,j=0,skipped=false;while(i<longer.length&&j<shorter.length){if(longer[i]===shorter[j]){i++;j++;continue}if(skipped)return false;skipped=true;i++}return true
}
function matchesKeyword(value,words){const normalized=normalizeKeyword(value);return words.some(word=>normalized===word||(normalized.length>=4&&word.length>=4&&isWithinOneEdit(normalized,word)))}
function apartmentSuffixLength(rest){for(const regex of[APARTMENT_NR_RE,APARTMENT_AFTER_RE]){regex.lastIndex=0;const match=regex.exec(rest);if(match&&matchesKeyword(match[1],APARTMENT_WORDS))return match[0].length}return 0}
export function findAddressMatches(value){const input=String(value??''),matches=[];ADDRESS_CANDIDATE_RE.lastIndex=0;let match;while((match=ADDRESS_CANDIDATE_RE.exec(input))){if(!matchesKeyword(match[1],ADDRESS_TYPE_WORDS))continue;const start=match.index,baseEnd=start+match[0].length,end=baseEnd+apartmentSuffixLength(input.slice(baseEnd));matches.push({matched:input.slice(start,end),relative:start});if(match[0].length===0)ADDRESS_CANDIDATE_RE.lastIndex++}return matches}
function freezeRule(rule){return Object.freeze({...rule,categories:Object.freeze([...rule.categories]),format:Object.freeze(rule.format),validation:Object.freeze(rule.validation)})}
export const BUILT_IN_SEMANTIC_RULES=Object.freeze([
 freezeRule({id:'person',type:'person',categories:['identity'],pl:'Imię i nazwisko',en:'Person name',risk:'high',mask:'[PERSON]',engine:'semantic',format:{pl:'Dwa człony imienia i nazwiska rozpoczynające się wielką literą',en:'Two capitalized person-name parts'},validation:{pl:'Kategoria tożsamościowa NPU + dokładny zakres',en:'NPU identity category + precise span'},re:/\b[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+\s+[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+\b/g}),
 freezeRule({id:'city',type:'city',categories:['identity'],pl:'Miejscowość',en:'City',risk:'high',mask:'[CITY]',engine:'semantic',format:{pl:'Nazwa miejscowości po przyimku w, we lub z',en:'Place name after in/from preposition'},validation:{pl:'Kategoria tożsamościowa NPU + kontekst przyimka',en:'NPU identity category + preposition context'},re:/\b(?:w|we|z)\s+([A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+)\b/g,capture:1}),
 freezeRule({id:'address',type:'address',categories:['identity'],pl:'Adres pocztowy',en:'Postal address',risk:'high',mask:'[ADDRESS]',engine:'semantic',format:{pl:'Typ ulicy, nazwa, numer budynku i opcjonalny lokal; słowa strukturalne tolerują jedną literówkę',en:'Street type, name, building and optional apartment; structural keywords tolerate one typo'},validation:{pl:'Kategoria tożsamościowa NPU + struktura adresu + maksymalnie jedna edycja w słowach technicznych',en:'NPU identity category + address structure + at most one edit in structural keywords'},re:ADDRESS_RE,find:findAddressMatches}),
 freezeRule({id:'medical',type:'medical',categories:['medical'],pl:'Informacja medyczna',en:'Medical information',risk:'high',mask:'[MEDICAL_INFO]',engine:'semantic',format:{pl:'Diagnoza lub choroba po frazach medycznych',en:'Diagnosis or condition after medical phrases'},validation:{pl:'Kategoria medyczna NPU + kontekst diagnozy',en:'NPU medical category + diagnosis context'},re:/\b(?:rozpoznał|rozpoznano|diagnoza:?|choruje na|cierpi na)\s+([^.!?]+)/giu,capture:1}),
 freezeRule({id:'medication',type:'medication',categories:['medical'],pl:'Nazwa leku',en:'Medication name',risk:'high',mask:'[MEDICATION]',engine:'semantic',format:{pl:'Nazwa preparatu po frazie zalecenia, przepisania lub przyjmowania',en:'Drug name after prescribe, recommend or take phrase'},validation:{pl:'Kategoria medyczna NPU + kontekst leczenia w tej samej linii',en:'NPU medical category + treatment context on the same line'},re:MEDICATION_RE,capture:1}),
 freezeRule({id:'amount',type:'amount',categories:['financial','employment'],pl:'Kwota finansowa',en:'Financial amount',risk:'high',mask:'[AMOUNT]',engine:'semantic',format:{pl:'Liczba z walutą, opcjonalnie brutto lub netto',en:'Number with currency and optional gross or net qualifier'},validation:{pl:'Kategoria finansowa lub pracownicza NPU + waluta',en:'NPU financial or employment category + currency'},re:/\b\d[\d\s.,]*\s*(?:zł|PLN|EUR|USD|€|\$)(?:\s+brutto|\s+netto)?\b/giu})
]);
const PATTERNS={};for(const rule of BUILT_IN_SEMANTIC_RULES)for(const category of rule.categories)(PATTERNS[category]??=[]).push(rule);
const MEDICATION_PATTERN=BUILT_IN_SEMANTIC_RULES.find(rule=>rule.id==='medication');
function lineColumn(text,index){const before=text.slice(0,index),lines=before.split('\n');return{line:lines.length,column:lines.at(-1).length+1}}
function lineRange(text,index){const start=text.lastIndexOf('\n',Math.max(0,index-1))+1,next=text.indexOf('\n',index);return{start,end:next<0?text.length:next}}
function patternMatches(pattern,value){if(pattern.find)return pattern.find(value);const matches=[];pattern.re.lastIndex=0;let match;while((match=pattern.re.exec(value))){const matched=pattern.capture?match[pattern.capture]:match[0],relative=match.index+(pattern.capture?match[0].indexOf(matched):0);matches.push({matched,relative});if(match[0].length===0)pattern.re.lastIndex++}return matches}
function collectMatches(text,value,baseStart,finding,patterns,spans,seen){for(const pattern of patterns)for(const match of patternMatches(pattern,value)){const start=baseStart+match.relative,end=start+match.matched.length,key=`${pattern.type}:${start}:${end}`;if(seen.has(key))continue;seen.add(key);const position=lineColumn(text,start);spans.push({type:pattern.type,value:match.matched,start,end,line:position.line,column:position.column,mask:pattern.mask,source:'semantic-span',risk:pattern.risk,score:finding.score,parentType:finding.type})}}
export function extractSemanticSpans(text,semanticFindings){const spans=[],seen=new Set();for(const finding of semanticFindings){collectMatches(text,finding.value,finding.start,finding,PATTERNS[finding.type]||[],spans,seen);if(finding.type==='medical'){const range=lineRange(text,finding.start);collectMatches(text,text.slice(range.start,range.end),range.start,finding,[MEDICATION_PATTERN],spans,seen)}}return spans.sort((a,b)=>a.start-b.start||a.end-b.end)}
export function selectRedactionSpans(items){const candidates=items.filter(item=>item.source!=='semantic-model').sort((a,b)=>a.start-b.start||(a.end-a.start)-(b.end-b.start)),selected=[];for(const item of candidates){if(selected.some(other=>item.start<other.end&&item.end>other.start))continue;selected.push(item)}return selected}
