const ADDRESS_TYPE=String.raw`(?:ul(?:ica|icy|icą|\.)?|aleja|alei|aleją|al\.|plac|placu|osiedle|osiedla|osiedlu|os\.)`;
const STREET_NAME=String.raw`[A-ZĄĆĘŁŃÓŚŹŻ][\p{L}-]+(?:\s+[A-ZĄĆĘŁŃÓŚŹŻ][\p{L}-]+)*`;
const BUILDING=String.raw`\d+[A-Za-z]?(?:\/\d+[A-Za-z]?)?(?:\s+m\.?\s*\d+[A-Za-z]?)?`;
const APARTMENT_SUFFIX=String.raw`(?:\s+(?:(?:w\s+)?mieszkaniu(?:\s+nr\.?)?|mieszkanie(?:\s+nr\.?)?|(?:w\s+)?lokalu(?:\s+nr\.?)?|lokal(?:\s+nr\.?)?|nr\.?\s+lokalu)\s+\d+[A-Za-z]?(?:\/\d+[A-Za-z]?)?)?`;
export const ADDRESS_RE=new RegExp(String.raw`\b${ADDRESS_TYPE}\s+${STREET_NAME}\s+${BUILDING}${APARTMENT_SUFFIX}\b`,'giu');
const MEDICATION_PREFIX=String.raw`(?:lek(?:u|iem|i)?|tablet(?:ka|ki|kę|ek|kami)?|preparat(?:u|em)?|branie(?:\s+tabletki)?|(?:zalecił|zaleciła|kazał|kazała)\s+(?:brać|stosować|przyjmować|zażywać)|przepisał|przepisała|stosować|przyjmować|zażywać)`;
export const MEDICATION_RE=new RegExp(String.raw`\b${MEDICATION_PREFIX}\s+(?:lek(?:u)?\s+|tablet(?:kę|ki|ka)\s+|preparat\s+)?((?!leczenie\b|lek(?:i|u)?\b|tablet(?:ka|ki|kę)\b)[\p{L}][\p{L}\d-]{2,})\b`,'giu');
const MEDICATION_PATTERN={type:'medication',mask:'[MEDICATION]',re:MEDICATION_RE,capture:1};
const PATTERNS={identity:[{type:'person',mask:'[PERSON]',re:/\b[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+\s+[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+\b/g},{type:'address',mask:'[ADDRESS]',re:ADDRESS_RE},{type:'city',mask:'[CITY]',re:/\b(?:w|we|z)\s+([A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+)\b/g,capture:1}],medical:[{type:'medical',mask:'[MEDICAL_INFO]',re:/\b(?:rozpoznał|rozpoznano|diagnoza:?|choruje na|cierpi na)\s+([^.!?]+)/giu,capture:1},MEDICATION_PATTERN],financial:[{type:'amount',mask:'[AMOUNT]',re:/\b\d[\d\s.,]*\s*(?:zł|PLN|EUR|USD|€|\$)(?:\s+brutto|\s+netto)?\b/giu}],employment:[{type:'amount',mask:'[AMOUNT]',re:/\b\d[\d\s.,]*\s*(?:zł|PLN|EUR|USD|€|\$)(?:\s+brutto|\s+netto)?\b/giu}],credentials:[]};
function lineColumn(text,index){const before=text.slice(0,index),lines=before.split('\n');return{line:lines.length,column:lines.at(-1).length+1}}
function lineRange(text,index){const start=text.lastIndexOf('\n',Math.max(0,index-1))+1,next=text.indexOf('\n',index);return{start,end:next<0?text.length:next}}
function collectMatches(text,value,baseStart,finding,patterns,spans,seen){for(const pattern of patterns){pattern.re.lastIndex=0;let match;while((match=pattern.re.exec(value))){const matched=pattern.capture?match[pattern.capture]:match[0];const local=match.index+(pattern.capture?match[0].indexOf(matched):0),start=baseStart+local,end=start+matched.length,key=`${pattern.type}:${start}:${end}`;if(!seen.has(key)){seen.add(key);const pos=lineColumn(text,start);spans.push({type:pattern.type,value:matched,start,end,line:pos.line,column:pos.column,mask:pattern.mask,source:'semantic-span',risk:'high',score:finding.score,parentType:finding.type})}if(match[0].length===0)pattern.re.lastIndex++}}}
export function extractSemanticSpans(text,semanticFindings){const spans=[],seen=new Set();for(const finding of semanticFindings){collectMatches(text,finding.value,finding.start,finding,PATTERNS[finding.type]||[],spans,seen);if(finding.type==='medical'){const range=lineRange(text,finding.start);collectMatches(text,text.slice(range.start,range.end),range.start,finding,[MEDICATION_PATTERN],spans,seen)}}return spans.sort((a,b)=>a.start-b.start||a.end-b.end)}
export function selectRedactionSpans(items){const candidates=items.filter(x=>x.source!=='semantic-model').sort((a,b)=>a.start-b.start||(a.end-a.start)-(b.end-b.start)),selected=[];for(const item of candidates){if(selected.some(x=>item.start<x.end&&item.end>x.start))continue;selected.push(item)}return selected}